
# This file is automatically generated, you probably don't want to edit this

CoefficientOfLineCorrelationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CoefficientOfLineCorrelationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            alpha = 0.05, ...) {

            super$initialize(
                package="Regression",
                name="CoefficientOfLineCorrelation",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..alpha)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        alpha = function() private$..alpha$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..alpha = NA)
)

CoefficientOfLineCorrelationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CoefficientOfLineCorrelationResults",
    inherit = jmvcore::Group,
    active = list(
        r = function() private$.items[["r"]],
        h0 = function() private$.items[["h0"]],
        ci = function() private$.items[["ci"]],
        r2 = function() private$.items[["r2"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Coefficient Of Line Correlation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="r",
                title="Coefficient of Line Correlation"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h0",
                title="$H_0: \\rho = 0$, No Linear Correlation"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="ci",
                title="Confidence Interval"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="r2",
                title="Coefficient of Determination"))}))

CoefficientOfLineCorrelationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CoefficientOfLineCorrelationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Regression",
                name = "CoefficientOfLineCorrelation",
                version = c(1,0,0),
                options = options,
                results = CoefficientOfLineCorrelationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Coefficient Of Line Correlation
#'
#' 
#' @param data .
#' @param x .
#' @param y .
#' @param alpha .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$r} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$h0} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ci} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$r2} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
CoefficientOfLineCorrelation <- function(
    data,
    x,
    y,
    alpha = 0.05) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("CoefficientOfLineCorrelation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL))


    options <- CoefficientOfLineCorrelationOptions$new(
        x = x,
        y = y,
        alpha = alpha)

    analysis <- CoefficientOfLineCorrelationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

