
# This file is automatically generated, you probably don't want to edit this

ComparisonOfTwoRegressionLinesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ComparisonOfTwoRegressionLinesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x1 = NULL,
            y1 = NULL,
            x2 = NULL,
            y2 = NULL,
            alpha = 0.05, ...) {

            super$initialize(
                package="Regression",
                name="ComparisonOfTwoRegressionLines",
                requiresData=TRUE,
                ...)

            private$..x1 <- jmvcore::OptionVariable$new(
                "x1",
                x1)
            private$..y1 <- jmvcore::OptionVariable$new(
                "y1",
                y1)
            private$..x2 <- jmvcore::OptionVariable$new(
                "x2",
                x2)
            private$..y2 <- jmvcore::OptionVariable$new(
                "y2",
                y2)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)

            self$.addOption(private$..x1)
            self$.addOption(private$..y1)
            self$.addOption(private$..x2)
            self$.addOption(private$..y2)
            self$.addOption(private$..alpha)
        }),
    active = list(
        x1 = function() private$..x1$value,
        y1 = function() private$..y1$value,
        x2 = function() private$..x2$value,
        y2 = function() private$..y2$value,
        alpha = function() private$..alpha$value),
    private = list(
        ..x1 = NA,
        ..y1 = NA,
        ..x2 = NA,
        ..y2 = NA,
        ..alpha = NA)
)

ComparisonOfTwoRegressionLinesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ComparisonOfTwoRegressionLinesResults",
    inherit = jmvcore::Group,
    active = list(
        cf = function() private$.items[["cf"]],
        ct = function() private$.items[["ct"]],
        iF = function() private$.items[["iF"]],
        iT = function() private$.items[["iT"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Comparison of Two Regression Lines")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cf",
                title="Comparison of Coefficients: F test"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="ct",
                title="Comparison of Coefficients: T test"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="iF",
                title="Comparison of Intercepts: F test"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="iT",
                title="Comparison of Intercepts: T test"))}))

ComparisonOfTwoRegressionLinesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ComparisonOfTwoRegressionLinesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Regression",
                name = "ComparisonOfTwoRegressionLines",
                version = c(1,0,0),
                options = options,
                results = ComparisonOfTwoRegressionLinesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Comparison of Two Regression Lines
#'
#' 
#' @param data .
#' @param x1 .
#' @param y1 .
#' @param x2 .
#' @param y2 .
#' @param alpha .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$cf} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ct} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$iF} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$iT} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
ComparisonOfTwoRegressionLines <- function(
    data,
    x1,
    y1,
    x2,
    y2,
    alpha = 0.05) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ComparisonOfTwoRegressionLines requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x1)) x1 <- jmvcore::resolveQuo(jmvcore::enquo(x1))
    if ( ! missing(y1)) y1 <- jmvcore::resolveQuo(jmvcore::enquo(y1))
    if ( ! missing(x2)) x2 <- jmvcore::resolveQuo(jmvcore::enquo(x2))
    if ( ! missing(y2)) y2 <- jmvcore::resolveQuo(jmvcore::enquo(y2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x1), x1, NULL),
            `if`( ! missing(y1), y1, NULL),
            `if`( ! missing(x2), x2, NULL),
            `if`( ! missing(y2), y2, NULL))


    options <- ComparisonOfTwoRegressionLinesOptions$new(
        x1 = x1,
        y1 = y1,
        x2 = x2,
        y2 = y2,
        alpha = alpha)

    analysis <- ComparisonOfTwoRegressionLinesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

