
# This file is automatically generated, you probably don't want to edit this

LinearRegressionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LinearRegressionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            a = "0.05",
            x0 = 0, ...) {

            super$initialize(
                package="Regression",
                name="LinearRegression",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.1"),
                default="0.05")
            private$..x0 <- jmvcore::OptionNumber$new(
                "x0",
                x0,
                default=0)

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..a)
            self$.addOption(private$..x0)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        a = function() private$..a$value,
        x0 = function() private$..x0$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..a = NA,
        ..x0 = NA)
)

LinearRegressionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LinearRegressionResults",
    inherit = jmvcore::Group,
    active = list(
        result = function() private$.items[["result"]],
        anova = function() private$.items[["anova"]],
        anovat = function() private$.items[["anovat"]],
        ttest = function() private$.items[["ttest"]],
        cl = function() private$.items[["cl"]],
        pm = function() private$.items[["pm"]],
        iy = function() private$.items[["iy"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Linear Regression")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="result",
                title="Linear Regression"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="anova",
                title="ANOVA"))
            self$add(jmvcore::Table$new(
                options=options,
                name="anovat",
                title="ANOVA Table",
                columns=list(
                    list(
                        `name`="vs", 
                        `title`="Variation Source", 
                        `type`="text"),
                    list(
                        `name`="df", 
                        `title`="$df$", 
                        `type`="integer"),
                    list(
                        `name`="ss", 
                        `title`="$SS$", 
                        `type`="number"),
                    list(
                        `name`="ms", 
                        `title`="$MS$", 
                        `type`="number"),
                    list(
                        `name`="F", 
                        `title`="$F$", 
                        `type`="number"),
                    list(
                        `name`="P", 
                        `title`="$P$", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="ttest",
                title="T-test"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cl",
                title="Confidence Interval of $\\beta$"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="pm",
                title="Confidence Interval of Population Mean $\\mu_\\{Y | X\\}$"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="iy",
                title="Prediction Interval of Individual $Y$ Value"))}))

LinearRegressionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LinearRegressionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Regression",
                name = "LinearRegression",
                version = c(1,0,0),
                options = options,
                results = LinearRegressionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Linear Regression
#'
#' 
#' @param data .
#' @param x .
#' @param y .
#' @param a .
#' @param x0 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$result} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$anova} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$anovat} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ttest} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cl} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$pm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$iy} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$anovat$asDF}
#'
#' \code{as.data.frame(results$anovat)}
#'
#' @export
LinearRegression <- function(
    data,
    x,
    y,
    a = "0.05",
    x0 = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("LinearRegression requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL))


    options <- LinearRegressionOptions$new(
        x = x,
        y = y,
        a = a,
        x0 = x0)

    analysis <- LinearRegressionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

