
# This file is automatically generated, you probably don't want to edit this

SpearmanRankCorrelationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SpearmanRankCorrelationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            alpha = 0.05,
            correct = NULL, ...) {

            super$initialize(
                package="Regression",
                name="SpearmanRankCorrelation",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..correct <- jmvcore::OptionBool$new(
                "correct",
                correct)

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..alpha)
            self$.addOption(private$..correct)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        alpha = function() private$..alpha$value,
        correct = function() private$..correct$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..alpha = NA,
        ..correct = NA)
)

SpearmanRankCorrelationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SpearmanRankCorrelationResults",
    inherit = jmvcore::Group,
    active = list(
        h0 = function() private$.items[["h0"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Spearman's Rank Correlation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h0",
                title="$H_0$: No Linear Correlation"))}))

SpearmanRankCorrelationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SpearmanRankCorrelationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Regression",
                name = "SpearmanRankCorrelation",
                version = c(1,0,0),
                options = options,
                results = SpearmanRankCorrelationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Spearman's Rank Correlation
#'
#' 
#' @param data .
#' @param x .
#' @param y .
#' @param alpha .
#' @param correct .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$h0} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
SpearmanRankCorrelation <- function(
    data,
    x,
    y,
    alpha = 0.05,
    correct) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SpearmanRankCorrelation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL))


    options <- SpearmanRankCorrelationOptions$new(
        x = x,
        y = y,
        alpha = alpha,
        correct = correct)

    analysis <- SpearmanRankCorrelationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

