
# This file is automatically generated, you probably don't want to edit this

KruskalWallisHTestForMultipleSamplesFrequencyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "KruskalWallisHTestForMultipleSamplesFrequencyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            f = NULL,
            a = "0.05", ...) {

            super$initialize(
                package="NonparametricTest",
                name="KruskalWallisHTestForMultipleSamplesFrequency",
                requiresData=TRUE,
                ...)

            private$..f <- jmvcore::OptionVariables$new(
                "f",
                f)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.10"),
                default="0.05")

            self$.addOption(private$..f)
            self$.addOption(private$..a)
        }),
    active = list(
        f = function() private$..f$value,
        a = function() private$..a$value),
    private = list(
        ..f = NA,
        ..a = NA)
)

KruskalWallisHTestForMultipleSamplesFrequencyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "KruskalWallisHTestForMultipleSamplesFrequencyResults",
    inherit = jmvcore::Group,
    active = list(
        h0 = function() private$.items[["h0"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Kruskal-Wallis H Test For Multiple Samples(Frequency)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h0",
                title=""))}))

KruskalWallisHTestForMultipleSamplesFrequencyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "KruskalWallisHTestForMultipleSamplesFrequencyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "NonparametricTest",
                name = "KruskalWallisHTestForMultipleSamplesFrequency",
                version = c(1,0,0),
                options = options,
                results = KruskalWallisHTestForMultipleSamplesFrequencyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Kruskal-Wallis H Test For Multiple Samples(Frequency)
#'
#' 
#' @param data .
#' @param f .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$h0} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
KruskalWallisHTestForMultipleSamplesFrequency <- function(
    data,
    f,
    a = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("KruskalWallisHTestForMultipleSamplesFrequency requires jmvcore to be installed (restart may be required)")

    if ( ! missing(f)) f <- jmvcore::resolveQuo(jmvcore::enquo(f))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(f), f, NULL))


    options <- KruskalWallisHTestForMultipleSamplesFrequencyOptions$new(
        f = f,
        a = a)

    analysis <- KruskalWallisHTestForMultipleSamplesFrequencyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

