
# This file is automatically generated, you probably don't want to edit this

NemenyiTestForMultipleIndependentSamplesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NemenyiTestForMultipleIndependentSamplesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            a = "0.05", ...) {

            super$initialize(
                package="NonparametricTest",
                name="NemenyiTestForMultipleIndependentSamples",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariables$new(
                "x",
                x)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.10"),
                default="0.05")

            self$.addOption(private$..x)
            self$.addOption(private$..a)
        }),
    active = list(
        x = function() private$..x$value,
        a = function() private$..a$value),
    private = list(
        ..x = NA,
        ..a = NA)
)

NemenyiTestForMultipleIndependentSamplesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NemenyiTestForMultipleIndependentSamplesResults",
    inherit = jmvcore::Group,
    active = list(
        h0 = function() private$.items[["h0"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Nemenyi Test For Multiple Independent Samples")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h0",
                title=""))}))

NemenyiTestForMultipleIndependentSamplesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NemenyiTestForMultipleIndependentSamplesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "NonparametricTest",
                name = "NemenyiTestForMultipleIndependentSamples",
                version = c(1,0,0),
                options = options,
                results = NemenyiTestForMultipleIndependentSamplesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Nemenyi Test For Multiple Independent Samples
#'
#' 
#' @param data .
#' @param x .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$h0} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
NemenyiTestForMultipleIndependentSamples <- function(
    data,
    x,
    a = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("NemenyiTestForMultipleIndependentSamples requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL))


    options <- NemenyiTestForMultipleIndependentSamplesOptions$new(
        x = x,
        a = a)

    analysis <- NemenyiTestForMultipleIndependentSamplesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

