
# This file is automatically generated, you probably don't want to edit this

WilcoxonSignedRankTestForPairedSamplesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "WilcoxonSignedRankTestForPairedSamplesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x1 = NULL,
            x2 = NULL,
            correct = TRUE,
            a = "0.05", ...) {

            super$initialize(
                package="NonparametricTest",
                name="WilcoxonSignedRankTestForPairedSamples",
                requiresData=TRUE,
                ...)

            private$..x1 <- jmvcore::OptionVariable$new(
                "x1",
                x1)
            private$..x2 <- jmvcore::OptionVariable$new(
                "x2",
                x2)
            private$..correct <- jmvcore::OptionBool$new(
                "correct",
                correct,
                default=TRUE)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.10"),
                default="0.05")

            self$.addOption(private$..x1)
            self$.addOption(private$..x2)
            self$.addOption(private$..correct)
            self$.addOption(private$..a)
        }),
    active = list(
        x1 = function() private$..x1$value,
        x2 = function() private$..x2$value,
        correct = function() private$..correct$value,
        a = function() private$..a$value),
    private = list(
        ..x1 = NA,
        ..x2 = NA,
        ..correct = NA,
        ..a = NA)
)

WilcoxonSignedRankTestForPairedSamplesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "WilcoxonSignedRankTestForPairedSamplesResults",
    inherit = jmvcore::Group,
    active = list(
        h0 = function() private$.items[["h0"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Wilcoxon Signed-Rank Test For Paired Samples")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h0",
                title=""))}))

WilcoxonSignedRankTestForPairedSamplesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "WilcoxonSignedRankTestForPairedSamplesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "NonparametricTest",
                name = "WilcoxonSignedRankTestForPairedSamples",
                version = c(1,0,0),
                options = options,
                results = WilcoxonSignedRankTestForPairedSamplesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Wilcoxon Signed-Rank Test For Paired Samples
#'
#' 
#' @param data .
#' @param x1 .
#' @param x2 .
#' @param correct .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$h0} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
WilcoxonSignedRankTestForPairedSamples <- function(
    data,
    x1,
    x2,
    correct = TRUE,
    a = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("WilcoxonSignedRankTestForPairedSamples requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x1)) x1 <- jmvcore::resolveQuo(jmvcore::enquo(x1))
    if ( ! missing(x2)) x2 <- jmvcore::resolveQuo(jmvcore::enquo(x2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x1), x1, NULL),
            `if`( ! missing(x2), x2, NULL))


    options <- WilcoxonSignedRankTestForPairedSamplesOptions$new(
        x1 = x1,
        x2 = x2,
        correct = correct,
        a = a)

    analysis <- WilcoxonSignedRankTestForPairedSamplesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

