
# This file is automatically generated, you probably don't want to edit this

BartlettTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BartlettTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            v = NULL,
            n = NULL,
            a = "0.05", ...) {

            super$initialize(
                package="ANOVA",
                name="BartlettTest",
                requiresData=TRUE,
                ...)

            private$..v <- jmvcore::OptionVariable$new(
                "v",
                v)
            private$..n <- jmvcore::OptionVariable$new(
                "n",
                n)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.10"),
                default="0.05")

            self$.addOption(private$..v)
            self$.addOption(private$..n)
            self$.addOption(private$..a)
        }),
    active = list(
        v = function() private$..v$value,
        n = function() private$..n$value,
        a = function() private$..a$value),
    private = list(
        ..v = NA,
        ..n = NA,
        ..a = NA)
)

BartlettTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BartlettTestResults",
    inherit = jmvcore::Group,
    active = list(
        conclusion = function() private$.items[["conclusion"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bartlett Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="conclusion",
                title=""))}))

BartlettTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BartlettTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ANOVA",
                name = "BartlettTest",
                version = c(1,0,0),
                options = options,
                results = BartlettTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bartlett Test
#'
#' 
#' @param data .
#' @param v .
#' @param n .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$conclusion} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
BartlettTest <- function(
    data,
    v,
    n,
    a = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BartlettTest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(v)) v <- jmvcore::resolveQuo(jmvcore::enquo(v))
    if ( ! missing(n)) n <- jmvcore::resolveQuo(jmvcore::enquo(n))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(v), v, NULL),
            `if`( ! missing(n), n, NULL))


    options <- BartlettTestOptions$new(
        v = v,
        n = n,
        a = a)

    analysis <- BartlettTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

