
# This file is automatically generated, you probably don't want to edit this

DunnettTTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DunnettTTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mi = NULL,
            ni = NULL,
            m0 = NULL,
            n0 = NULL,
            ve = NULL,
            t = NULL,
            mse = NULL,
            a = "0.0250", ...) {

            super$initialize(
                package="ANOVA",
                name="DunnettTTest",
                requiresData=TRUE,
                ...)

            private$..mi <- jmvcore::OptionNumber$new(
                "mi",
                mi)
            private$..ni <- jmvcore::OptionNumber$new(
                "ni",
                ni)
            private$..m0 <- jmvcore::OptionNumber$new(
                "m0",
                m0)
            private$..n0 <- jmvcore::OptionNumber$new(
                "n0",
                n0)
            private$..ve <- jmvcore::OptionNumber$new(
                "ve",
                ve)
            private$..t <- jmvcore::OptionNumber$new(
                "t",
                t)
            private$..mse <- jmvcore::OptionNumber$new(
                "mse",
                mse)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.0050",
                    "0.0250",
                    "0.050"),
                default="0.0250")

            self$.addOption(private$..mi)
            self$.addOption(private$..ni)
            self$.addOption(private$..m0)
            self$.addOption(private$..n0)
            self$.addOption(private$..ve)
            self$.addOption(private$..t)
            self$.addOption(private$..mse)
            self$.addOption(private$..a)
        }),
    active = list(
        mi = function() private$..mi$value,
        ni = function() private$..ni$value,
        m0 = function() private$..m0$value,
        n0 = function() private$..n0$value,
        ve = function() private$..ve$value,
        t = function() private$..t$value,
        mse = function() private$..mse$value,
        a = function() private$..a$value),
    private = list(
        ..mi = NA,
        ..ni = NA,
        ..m0 = NA,
        ..n0 = NA,
        ..ve = NA,
        ..t = NA,
        ..mse = NA,
        ..a = NA)
)

DunnettTTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DunnettTTestResults",
    inherit = jmvcore::Group,
    active = list(
        conclusion = function() private$.items[["conclusion"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Dunnett-T Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="conclusion",
                title="Dunnett-T Test"))}))

DunnettTTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DunnettTTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ANOVA",
                name = "DunnettTTest",
                version = c(1,0,0),
                options = options,
                results = DunnettTTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Dunnett-T Test
#'
#' 
#' @param data .
#' @param mi .
#' @param ni .
#' @param m0 .
#' @param n0 .
#' @param ve .
#' @param t .
#' @param mse .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$conclusion} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
DunnettTTest <- function(
    data,
    mi,
    ni,
    m0,
    n0,
    ve,
    t,
    mse,
    a = "0.0250") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("DunnettTTest requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- DunnettTTestOptions$new(
        mi = mi,
        ni = ni,
        m0 = m0,
        n0 = n0,
        ve = ve,
        t = t,
        mse = mse,
        a = a)

    analysis <- DunnettTTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

