
# This file is automatically generated, you probably don't want to edit this

OneFactorANOVAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "OneFactorANOVAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            a = "0.05", ...) {

            super$initialize(
                package="ANOVA",
                name="OneFactorANOVA",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariables$new(
                "x",
                x)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.10"),
                default="0.05")

            self$.addOption(private$..x)
            self$.addOption(private$..a)
        }),
    active = list(
        x = function() private$..x$value,
        a = function() private$..a$value),
    private = list(
        ..x = NA,
        ..a = NA)
)

OneFactorANOVAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "OneFactorANOVAResults",
    inherit = jmvcore::Group,
    active = list(
        anova = function() private$.items[["anova"]],
        conclusion = function() private$.items[["conclusion"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One-Factor ANOVA")
            self$add(jmvcore::Table$new(
                options=options,
                name="anova",
                title="One-Factor ANOVA",
                columns=list(
                    list(
                        `name`="sv", 
                        `title`="Sources Of Variation", 
                        `type`="text"),
                    list(
                        `name`="v", 
                        `title`="$v$", 
                        `type`="integer"),
                    list(
                        `name`="ss", 
                        `title`="$SS$", 
                        `type`="number"),
                    list(
                        `name`="ms", 
                        `title`="$MS$", 
                        `type`="number"),
                    list(
                        `name`="f", 
                        `title`="$F$", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="$P$", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="conclusion",
                title="Conclusion"))}))

OneFactorANOVABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "OneFactorANOVABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ANOVA",
                name = "OneFactorANOVA",
                version = c(1,0,0),
                options = options,
                results = OneFactorANOVAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' One-Factor ANOVA
#'
#' 
#' @param data .
#' @param x .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$anova} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$conclusion} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$anova$asDF}
#'
#' \code{as.data.frame(results$anova)}
#'
#' @export
OneFactorANOVA <- function(
    data,
    x,
    a = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("OneFactorANOVA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL))


    options <- OneFactorANOVAOptions$new(
        x = x,
        a = a)

    analysis <- OneFactorANOVAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

