
# This file is automatically generated, you probably don't want to edit this

SNKQTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SNKQTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            m = NULL,
            n = NULL,
            g = NULL,
            mse = NULL,
            ve = NULL,
            a = "0.05", ...) {

            super$initialize(
                package="ANOVA",
                name="SNKQTest",
                requiresData=TRUE,
                ...)

            private$..m <- jmvcore::OptionVariable$new(
                "m",
                m)
            private$..n <- jmvcore::OptionVariable$new(
                "n",
                n)
            private$..g <- jmvcore::OptionVariable$new(
                "g",
                g,
                suggested=list(
                    "nominal"))
            private$..mse <- jmvcore::OptionNumber$new(
                "mse",
                mse)
            private$..ve <- jmvcore::OptionNumber$new(
                "ve",
                ve)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.10"),
                default="0.05")

            self$.addOption(private$..m)
            self$.addOption(private$..n)
            self$.addOption(private$..g)
            self$.addOption(private$..mse)
            self$.addOption(private$..ve)
            self$.addOption(private$..a)
        }),
    active = list(
        m = function() private$..m$value,
        n = function() private$..n$value,
        g = function() private$..g$value,
        mse = function() private$..mse$value,
        ve = function() private$..ve$value,
        a = function() private$..a$value),
    private = list(
        ..m = NA,
        ..n = NA,
        ..g = NA,
        ..mse = NA,
        ..ve = NA,
        ..a = NA)
)

SNKQTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SNKQTestResults",
    inherit = jmvcore::Group,
    active = list(
        qt = function() private$.items[["qt"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="SNK-q Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="qt",
                title="SNK-q Test",
                columns=list(
                    list(
                        `name`="cg", 
                        `title`="$i,j$", 
                        `type`="text"),
                    list(
                        `name`="md", 
                        `title`="$\\overline X_i-\\overline X_j$", 
                        `type`="number"),
                    list(
                        `name`="a", 
                        `title`="$a$", 
                        `type`="integer"),
                    list(
                        `name`="q", 
                        `title`="$q$", 
                        `type`="number"),
                    list(
                        `name`="qa", 
                        `title`="$q_\\alpha$", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="$P$", 
                        `type`="number"),
                    list(
                        `name`="h0", 
                        `title`="$H_0(\\mu_i=\\mu_j)$", 
                        `type`="text"))))}))

SNKQTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SNKQTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ANOVA",
                name = "SNKQTest",
                version = c(1,0,0),
                options = options,
                results = SNKQTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' SNK-q Test
#'
#' 
#' @param data .
#' @param m .
#' @param n .
#' @param g .
#' @param mse .
#' @param ve .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$qt} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$qt$asDF}
#'
#' \code{as.data.frame(results$qt)}
#'
#' @export
SNKQTest <- function(
    data,
    m,
    n,
    g,
    mse,
    ve,
    a = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SNKQTest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(m)) m <- jmvcore::resolveQuo(jmvcore::enquo(m))
    if ( ! missing(n)) n <- jmvcore::resolveQuo(jmvcore::enquo(n))
    if ( ! missing(g)) g <- jmvcore::resolveQuo(jmvcore::enquo(g))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(m), m, NULL),
            `if`( ! missing(n), n, NULL),
            `if`( ! missing(g), g, NULL))


    options <- SNKQTestOptions$new(
        m = m,
        n = n,
        g = g,
        mse = mse,
        ve = ve,
        a = a)

    analysis <- SNKQTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

