
# This file is automatically generated, you probably don't want to edit this

ThreeWayClassificationANOVAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ThreeWayClassificationANOVAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            k = NULL,
            a = "0.05", ...) {

            super$initialize(
                package="ANOVA",
                name="ThreeWayClassificationANOVA",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariables$new(
                "x",
                x)
            private$..k <- jmvcore::OptionVariables$new(
                "k",
                k,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.10"),
                default="0.05")

            self$.addOption(private$..x)
            self$.addOption(private$..k)
            self$.addOption(private$..a)
        }),
    active = list(
        x = function() private$..x$value,
        k = function() private$..k$value,
        a = function() private$..a$value),
    private = list(
        ..x = NA,
        ..k = NA,
        ..a = NA)
)

ThreeWayClassificationANOVAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ThreeWayClassificationANOVAResults",
    inherit = jmvcore::Group,
    active = list(
        anova = function() private$.items[["anova"]],
        h01 = function() private$.items[["h01"]],
        h02 = function() private$.items[["h02"]],
        h03 = function() private$.items[["h03"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Three-Way Classificiation ANOVA")
            self$add(jmvcore::Table$new(
                options=options,
                name="anova",
                title="Three-Way Classificiation ANOVA",
                columns=list(
                    list(
                        `name`="sv", 
                        `title`="Sources Of Variation", 
                        `type`="text"),
                    list(
                        `name`="v", 
                        `title`="$v$", 
                        `type`="integer"),
                    list(
                        `name`="ss", 
                        `title`="$SS$", 
                        `type`="number"),
                    list(
                        `name`="ms", 
                        `title`="$MS$", 
                        `type`="number"),
                    list(
                        `name`="f", 
                        `title`="$F$", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="$P$", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h01",
                title=""))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h02",
                title=""))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h03",
                title=""))}))

ThreeWayClassificationANOVABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ThreeWayClassificationANOVABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ANOVA",
                name = "ThreeWayClassificationANOVA",
                version = c(1,0,0),
                options = options,
                results = ThreeWayClassificationANOVAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Three-Way Classificiation ANOVA
#'
#' 
#' @param data .
#' @param x .
#' @param k .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$anova} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$h01} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$h02} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$h03} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$anova$asDF}
#'
#' \code{as.data.frame(results$anova)}
#'
#' @export
ThreeWayClassificationANOVA <- function(
    data,
    x,
    k,
    a = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ThreeWayClassificationANOVA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(k)) k <- jmvcore::resolveQuo(jmvcore::enquo(k))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(k), k, NULL))

    for (v in k) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- ThreeWayClassificationANOVAOptions$new(
        x = x,
        k = k,
        a = a)

    analysis <- ThreeWayClassificationANOVAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

