
# This file is automatically generated, you probably don't want to edit this

TwoWayANOVAWithFactorialDesignOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "TwoWayANOVAWithFactorialDesignOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            value = NULL,
            la = NULL,
            lb = NULL, ...) {

            super$initialize(
                package="ANOVA",
                name="TwoWayANOVAWithFactorialDesign",
                requiresData=TRUE,
                ...)

            private$..value <- jmvcore::OptionVariable$new(
                "value",
                value)
            private$..la <- jmvcore::OptionVariable$new(
                "la",
                la)
            private$..lb <- jmvcore::OptionVariable$new(
                "lb",
                lb)

            self$.addOption(private$..value)
            self$.addOption(private$..la)
            self$.addOption(private$..lb)
        }),
    active = list(
        value = function() private$..value$value,
        la = function() private$..la$value,
        lb = function() private$..lb$value),
    private = list(
        ..value = NA,
        ..la = NA,
        ..lb = NA)
)

TwoWayANOVAWithFactorialDesignResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "TwoWayANOVAWithFactorialDesignResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Two-way ANOVA with factorial design")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Two-way ANOVA with factorial design"))}))

TwoWayANOVAWithFactorialDesignBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "TwoWayANOVAWithFactorialDesignBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ANOVA",
                name = "TwoWayANOVAWithFactorialDesign",
                version = c(1,0,0),
                options = options,
                results = TwoWayANOVAWithFactorialDesignResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Two-way ANOVA with factorial design
#'
#' 
#' @param data .
#' @param value .
#' @param la .
#' @param lb .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
TwoWayANOVAWithFactorialDesign <- function(
    data,
    value,
    la,
    lb) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("TwoWayANOVAWithFactorialDesign requires jmvcore to be installed (restart may be required)")

    if ( ! missing(value)) value <- jmvcore::resolveQuo(jmvcore::enquo(value))
    if ( ! missing(la)) la <- jmvcore::resolveQuo(jmvcore::enquo(la))
    if ( ! missing(lb)) lb <- jmvcore::resolveQuo(jmvcore::enquo(lb))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(value), value, NULL),
            `if`( ! missing(la), la, NULL),
            `if`( ! missing(lb), lb, NULL))


    options <- TwoWayANOVAWithFactorialDesignOptions$new(
        value = value,
        la = la,
        lb = lb)

    analysis <- TwoWayANOVAWithFactorialDesignClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

