
# This file is automatically generated, you probably don't want to edit this

CertifiedValueOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CertifiedValueOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            a = "0.05", ...) {

            super$initialize(
                package="CommutabilityAndStability",
                name="CertifiedValue",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariables$new(
                "x",
                x)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.10"),
                default="0.05")

            self$.addOption(private$..x)
            self$.addOption(private$..a)
        }),
    active = list(
        x = function() private$..x$value,
        a = function() private$..a$value),
    private = list(
        ..x = NA,
        ..a = NA)
)

CertifiedValueResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CertifiedValueResults",
    inherit = jmvcore::Group,
    active = list(
        st = function() private$.items[["st"]],
        kst = function() private$.items[["kst"]],
        gtr = function() private$.items[["gtr"]],
        cv = function() private$.items[["cv"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Certified value")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="st",
                title="Normality test"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="kst",
                title="Normality test"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="gtr",
                title="Grubbs test"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cv",
                title="Certified value"))}))

CertifiedValueBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CertifiedValueBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CommutabilityAndStability",
                name = "CertifiedValue",
                version = c(1,0,0),
                options = options,
                results = CertifiedValueResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Certified value
#'
#' 
#' @param data .
#' @param x .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$st} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$kst} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$gtr} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cv} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
CertifiedValue <- function(
    data,
    x,
    a = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("CertifiedValue requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL))


    options <- CertifiedValueOptions$new(
        x = x,
        a = a)

    analysis <- CertifiedValueClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

