
# This file is automatically generated, you probably don't want to edit this

CSUOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CSUOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            uchar = NULL,
            ubb = NULL,
            ust1 = NULL,
            ust2 = NULL,
            ust3 = NULL,
            ust4 = NULL,
            ust5 = NULL,
            ust6 = NULL,
            k = 2, ...) {

            super$initialize(
                package="CommutabilityAndStability",
                name="CSU",
                requiresData=TRUE,
                ...)

            private$..uchar <- jmvcore::OptionNumber$new(
                "uchar",
                uchar)
            private$..ubb <- jmvcore::OptionNumber$new(
                "ubb",
                ubb)
            private$..ust1 <- jmvcore::OptionNumber$new(
                "ust1",
                ust1)
            private$..ust2 <- jmvcore::OptionNumber$new(
                "ust2",
                ust2)
            private$..ust3 <- jmvcore::OptionNumber$new(
                "ust3",
                ust3)
            private$..ust4 <- jmvcore::OptionNumber$new(
                "ust4",
                ust4)
            private$..ust5 <- jmvcore::OptionNumber$new(
                "ust5",
                ust5)
            private$..ust6 <- jmvcore::OptionNumber$new(
                "ust6",
                ust6)
            private$..k <- jmvcore::OptionNumber$new(
                "k",
                k,
                default=2)

            self$.addOption(private$..uchar)
            self$.addOption(private$..ubb)
            self$.addOption(private$..ust1)
            self$.addOption(private$..ust2)
            self$.addOption(private$..ust3)
            self$.addOption(private$..ust4)
            self$.addOption(private$..ust5)
            self$.addOption(private$..ust6)
            self$.addOption(private$..k)
        }),
    active = list(
        uchar = function() private$..uchar$value,
        ubb = function() private$..ubb$value,
        ust1 = function() private$..ust1$value,
        ust2 = function() private$..ust2$value,
        ust3 = function() private$..ust3$value,
        ust4 = function() private$..ust4$value,
        ust5 = function() private$..ust5$value,
        ust6 = function() private$..ust6$value,
        k = function() private$..k$value),
    private = list(
        ..uchar = NA,
        ..ubb = NA,
        ..ust1 = NA,
        ..ust2 = NA,
        ..ust3 = NA,
        ..ust4 = NA,
        ..ust5 = NA,
        ..ust6 = NA,
        ..k = NA)
)

CSUResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CSUResults",
    inherit = jmvcore::Group,
    active = list(
        uc = function() private$.items[["uc"]],
        u = function() private$.items[["u"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Combined standard uncertainty")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="uc",
                title="Combined standard uncertainty"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="u",
                title="Combined expanded uncertainty"))}))

CSUBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CSUBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CommutabilityAndStability",
                name = "CSU",
                version = c(1,0,0),
                options = options,
                results = CSUResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Combined standard uncertainty
#'
#' 
#' @param data .
#' @param uchar .
#' @param ubb .
#' @param ust1 .
#' @param ust2 .
#' @param ust3 .
#' @param ust4 .
#' @param ust5 .
#' @param ust6 .
#' @param k .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$uc} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$u} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
CSU <- function(
    data,
    uchar,
    ubb,
    ust1,
    ust2,
    ust3,
    ust4,
    ust5,
    ust6,
    k = 2) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("CSU requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- CSUOptions$new(
        uchar = uchar,
        ubb = ubb,
        ust1 = ust1,
        ust2 = ust2,
        ust3 = ust3,
        ust4 = ust4,
        ust5 = ust5,
        ust6 = ust6,
        k = k)

    analysis <- CSUClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

