
# This file is automatically generated, you probably don't want to edit this

FTSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FTSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL, ...) {

            super$initialize(
                package="CommutabilityAndStability",
                name="FTS",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariables$new(
                "y",
                y)

            self$.addOption(private$..x)
            self$.addOption(private$..y)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value),
    private = list(
        ..x = NA,
        ..y = NA)
)

FTSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FTSResults",
    inherit = jmvcore::Group,
    active = list(
        fts = function() private$.items[["fts"]],
        t = function() private$.items[["t"]],
        sb1 = function() private$.items[["sb1"]],
        b1 = function() private$.items[["b1"]],
        s = function() private$.items[["s"]],
        xi = function() private$.items[["xi"]],
        xm = function() private$.items[["xm"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Freeze-thaw stability")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="fts",
                title="Freeze-thaw stability"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="t",
                title="$t$: Time points"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="sb1",
                title="$s(b_1)$: Uncertainty of slope"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="b1",
                title="$b_1$: Intercept"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="s",
                title="$s$: Standard deviation of straight line"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="xi",
                title="$x_i$: Time point"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="xm",
                title="$\\\\overline x$: Mean of time point"))}))

FTSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FTSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CommutabilityAndStability",
                name = "FTS",
                version = c(1,0,0),
                options = options,
                results = FTSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Freeze-thaw stability
#'
#' 
#' @param data .
#' @param x .
#' @param y .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$fts} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$t} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sb1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$b1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$s} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$xi} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$xm} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
FTS <- function(
    data,
    x,
    y) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("FTS requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL))


    options <- FTSOptions$new(
        x = x,
        y = y)

    analysis <- FTSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

