
# This file is automatically generated, you probably don't want to edit this

homogeneityOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "homogeneityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            target = NULL, ...) {

            super$initialize(
                package="Proficiency",
                name="homogeneity",
                requiresData=TRUE,
                ...)

            private$..target <- jmvcore::OptionVariables$new(
                "target",
                target)

            self$.addOption(private$..target)
        }),
    active = list(
        target = function() private$..target$value),
    private = list(
        ..target = NA)
)

homogeneityResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "homogeneityResults",
    inherit = jmvcore::Group,
    active = list(
        result = function() private$.items[["result"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Uniformity analysis")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="result",
                title="result"))}))

homogeneityBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "homogeneityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Proficiency",
                name = "homogeneity",
                version = c(1,0,0),
                options = options,
                results = homogeneityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Uniformity analysis
#'
#' 
#' @param data .
#' @param target .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$result} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
homogeneity <- function(
    data,
    target) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("homogeneity requires jmvcore to be installed (restart may be required)")

    if ( ! missing(target)) target <- jmvcore::resolveQuo(jmvcore::enquo(target))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(target), target, NULL))


    options <- homogeneityOptions$new(
        target = target)

    analysis <- homogeneityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

