
# This file is automatically generated, you probably don't want to edit this

AccuracyEvaluationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "AccuracyEvaluationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            l = NULL,
            x = NULL,
            y = NULL,
            rs = list(
                list(l=1, r=1.5, u=0.1),
                list(l=2, r=2, u=0.1),
                list(l=3, r=2.5, u=0.1)),
            cf = 2,
            unit = "%",
            c = 6, ...) {

            super$initialize(
                package="ReferenceMaterial",
                name="AccuracyEvaluation",
                requiresData=TRUE,
                ...)

            private$..l <- jmvcore::OptionVariable$new(
                "l",
                l)
            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y)
            private$..rs <- jmvcore::OptionArray$new(
                "rs",
                rs,
                default=list(
                    list(l=1, r=1.5, u=0.1),
                    list(l=2, r=2, u=0.1),
                    list(l=3, r=2.5, u=0.1)),
                template=jmvcore::OptionGroup$new(
                    "rs",
                    NULL,
                    elements=list(
                        jmvcore::OptionInteger$new(
                            "l",
                            NULL),
                        jmvcore::OptionNumber$new(
                            "r",
                            NULL),
                        jmvcore::OptionNumber$new(
                            "u",
                            NULL))))
            private$..cf <- jmvcore::OptionNumber$new(
                "cf",
                cf,
                default=2)
            private$..unit <- jmvcore::OptionString$new(
                "unit",
                unit,
                default="%")
            private$..c <- jmvcore::OptionNumber$new(
                "c",
                c,
                default=6)

            self$.addOption(private$..l)
            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..rs)
            self$.addOption(private$..cf)
            self$.addOption(private$..unit)
            self$.addOption(private$..c)
        }),
    active = list(
        l = function() private$..l$value,
        x = function() private$..x$value,
        y = function() private$..y$value,
        rs = function() private$..rs$value,
        cf = function() private$..cf$value,
        unit = function() private$..unit$value,
        c = function() private$..c$value),
    private = list(
        ..l = NA,
        ..x = NA,
        ..y = NA,
        ..rs = NA,
        ..cf = NA,
        ..unit = NA,
        ..c = NA)
)

AccuracyEvaluationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "AccuracyEvaluationResults",
    inherit = jmvcore::Group,
    active = list(
        test = function() private$.items[["test"]],
        tt = function() private$.items[["tt"]],
        t = function() private$.items[["t"]],
        n = function() private$.items[["n"]],
        c = function() private$.items[["c"]],
        w = function() private$.items[["w"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Accuracy",
                refs=list(
                    "ep10a3"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="test",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="tt",
                title="*Result table:"))
            self$add(jmvcore::Table$new(
                options=options,
                name="t",
                title="Accuracy of difference measurement procedure",
                columns=list(
                    list(
                        `name`="l", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="v", 
                        `title`="Reference value", 
                        `type`="text"),
                    list(
                        `name`="mx", 
                        `title`="Mean", 
                        `type`="number", 
                        `superTitle`="MP$_X$"),
                    list(
                        `name`="sdx", 
                        `title`="$SD$", 
                        `type`="number", 
                        `superTitle`="MP$_X$"),
                    list(
                        `name`="rdx", 
                        `title`="$RD$ (%)", 
                        `type`="number", 
                        `superTitle`="MP$_X$"),
                    list(
                        `name`="my", 
                        `title`="Mean", 
                        `type`="number", 
                        `superTitle`="MP$_Y$"),
                    list(
                        `name`="sdy", 
                        `title`="$SD$", 
                        `type`="number", 
                        `superTitle`="MP$_Y$"),
                    list(
                        `name`="rdy", 
                        `title`="$RD$ (%)", 
                        `type`="number", 
                        `superTitle`="MP$_Y$"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="n"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="c",
                title="*Conclusion:"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="w",
                title="*Warning:",
                visible=FALSE))}))

AccuracyEvaluationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "AccuracyEvaluationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ReferenceMaterial",
                name = "AccuracyEvaluation",
                version = c(1,0,0),
                options = options,
                results = AccuracyEvaluationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Accuracy
#'
#' 
#' @param data .
#' @param l .
#' @param x .
#' @param y .
#' @param rs .
#' @param cf .
#' @param unit .
#' @param c .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$test} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$tt} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$t} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$n} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$c} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$w} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$t$asDF}
#'
#' \code{as.data.frame(results$t)}
#'
#' @export
AccuracyEvaluation <- function(
    data,
    l,
    x,
    y,
    rs = list(
                list(l=1, r=1.5, u=0.1),
                list(l=2, r=2, u=0.1),
                list(l=3, r=2.5, u=0.1)),
    cf = 2,
    unit = "%",
    c = 6) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("AccuracyEvaluation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(l)) l <- jmvcore::resolveQuo(jmvcore::enquo(l))
    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(l), l, NULL),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL))


    options <- AccuracyEvaluationOptions$new(
        l = l,
        x = x,
        y = y,
        rs = rs,
        cf = cf,
        unit = unit,
        c = c)

    analysis <- AccuracyEvaluationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

