
# This file is automatically generated, you probably don't want to edit this

CommuntabilityEP30ABiasOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CommuntabilityEP30ABiasOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            csid = NULL,
            csx = NULL,
            csy = NULL,
            rmid = NULL,
            rmp = NULL,
            rmx = NULL,
            rmy = NULL,
            ln = NULL,
            logscale = TRUE,
            ef = 1.9,
            alpha = 0.05,
            g.alpha = 0.01,
            C = 12,
            mt = "HbA1c",
            unit = "mg/L", ...) {

            super$initialize(
                package="ReferenceMaterial",
                name="CommuntabilityEP30ABias",
                requiresData=TRUE,
                ...)

            private$..csid <- jmvcore::OptionVariable$new(
                "csid",
                csid)
            private$..csx <- jmvcore::OptionVariables$new(
                "csx",
                csx)
            private$..csy <- jmvcore::OptionVariables$new(
                "csy",
                csy)
            private$..rmid <- jmvcore::OptionVariable$new(
                "rmid",
                rmid)
            private$..rmp <- jmvcore::OptionVariable$new(
                "rmp",
                rmp)
            private$..rmx <- jmvcore::OptionVariables$new(
                "rmx",
                rmx)
            private$..rmy <- jmvcore::OptionVariables$new(
                "rmy",
                rmy)
            private$..ln <- jmvcore::OptionBool$new(
                "ln",
                ln)
            private$..logscale <- jmvcore::OptionBool$new(
                "logscale",
                logscale,
                default=TRUE)
            private$..ef <- jmvcore::OptionNumber$new(
                "ef",
                ef,
                default=1.9)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..g.alpha <- jmvcore::OptionNumber$new(
                "g.alpha",
                g.alpha,
                default=0.01)
            private$..C <- jmvcore::OptionNumber$new(
                "C",
                C,
                default=12)
            private$..mt <- jmvcore::OptionString$new(
                "mt",
                mt,
                default="HbA1c")
            private$..unit <- jmvcore::OptionString$new(
                "unit",
                unit,
                default="mg/L")

            self$.addOption(private$..csid)
            self$.addOption(private$..csx)
            self$.addOption(private$..csy)
            self$.addOption(private$..rmid)
            self$.addOption(private$..rmp)
            self$.addOption(private$..rmx)
            self$.addOption(private$..rmy)
            self$.addOption(private$..ln)
            self$.addOption(private$..logscale)
            self$.addOption(private$..ef)
            self$.addOption(private$..alpha)
            self$.addOption(private$..g.alpha)
            self$.addOption(private$..C)
            self$.addOption(private$..mt)
            self$.addOption(private$..unit)
        }),
    active = list(
        csid = function() private$..csid$value,
        csx = function() private$..csx$value,
        csy = function() private$..csy$value,
        rmid = function() private$..rmid$value,
        rmp = function() private$..rmp$value,
        rmx = function() private$..rmx$value,
        rmy = function() private$..rmy$value,
        ln = function() private$..ln$value,
        logscale = function() private$..logscale$value,
        ef = function() private$..ef$value,
        alpha = function() private$..alpha$value,
        g.alpha = function() private$..g.alpha$value,
        C = function() private$..C$value,
        mt = function() private$..mt$value,
        unit = function() private$..unit$value),
    private = list(
        ..csid = NA,
        ..csx = NA,
        ..csy = NA,
        ..rmid = NA,
        ..rmp = NA,
        ..rmx = NA,
        ..rmy = NA,
        ..ln = NA,
        ..logscale = NA,
        ..ef = NA,
        ..alpha = NA,
        ..g.alpha = NA,
        ..C = NA,
        ..mt = NA,
        ..unit = NA)
)

CommuntabilityEP30ABiasResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CommuntabilityEP30ABiasResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        mr = function() private$.items[["mr"]],
        abb = function() private$.items[["abb"]],
        symbols = function() private$.items[["symbols"]],
        descriptive = function() private$.items[["descriptive"]],
        cvrm = function() private$.items[["cvrm"]],
        cmp = function() private$.items[["cmp"]],
        ttcs = function() private$.items[["ttcs"]],
        tdcs = function() private$.items[["tdcs"]],
        rma = function() private$.items[["rma"]],
        sec = function() private$.items[["sec"]],
        seft = function() private$.items[["seft"]],
        adj = function() private$.items[["adj"]],
        ct = function() private$.items[["ct"]],
        ci = function() private$.items[["ci"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Commutability (CLSI, EP30-A2-B)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="text",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mr",
                title="Method reference"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="abb",
                title="Abbreviations"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="symbols",
                title="Symbols"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    o = function() private$.items[["o"]],
                    mc = function() private$.items[["mc"]],
                    v = function() private$.items[["v"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="descriptive",
                            title="Descriptive of data")
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                cs = function() private$.items[["cs"]],
                                csc = function() private$.items[["csc"]],
                                rm = function() private$.items[["rm"]],
                                rmc = function() private$.items[["rmc"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="o",
                                        title="Outliers of data")
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="cs",
                                        title="Outliers of clinical samples",
                                        visible=FALSE,
                                        columns=list(
                                            list(
                                                `name`="cs.id", 
                                                `title`="ID", 
                                                `type`="text"),
                                            list(
                                                `name`="v", 
                                                `title`="Value", 
                                                `type`="number"))))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="csc",
                                        title="*Clinical samples' conclusion:"))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="rm",
                                        title="Outliers of reference materials",
                                        visible=FALSE,
                                        columns=list(
                                            list(
                                                `name`="rm.id", 
                                                `title`="ID", 
                                                `type`="text"),
                                            list(
                                                `name`="pos", 
                                                `title`="Position", 
                                                `type`="text"),
                                            list(
                                                `name`="v", 
                                                `title`="Value", 
                                                `type`="number"))))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="rmc",
                                        title="*Reference materials' conclusion:"))}))$new(options=options))
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                rm = function() private$.items[["rm"]],
                                cs = function() private$.items[["cs"]],
                                c = function() private$.items[["c"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="mc",
                                        title="Mean and standard deviation of data")
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="rm",
                                        title="Reference materials",
                                        columns=list(
                                            list(
                                                `name`="rm.id", 
                                                `title`="ID", 
                                                `type`="text"),
                                            list(
                                                `name`="mx", 
                                                `title`="$X$", 
                                                `type`="number", 
                                                `superTitle`="Mean"),
                                            list(
                                                `name`="my", 
                                                `title`="$Y$", 
                                                `type`="number", 
                                                `superTitle`="Mean"),
                                            list(
                                                `name`="xy", 
                                                `title`="$(X+Y)/2$", 
                                                `type`="number", 
                                                `superTitle`="Mean"),
                                            list(
                                                `name`="sdx", 
                                                `title`="$X$", 
                                                `type`="number", 
                                                `superTitle`="Standard deviation"),
                                            list(
                                                `name`="sdy", 
                                                `title`="$Y$", 
                                                `type`="number", 
                                                `superTitle`="Standard deviation"))))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="cs",
                                        title="Clinical samples",
                                        columns=list(
                                            list(
                                                `name`="cs.id", 
                                                `title`="ID", 
                                                `type`="text"),
                                            list(
                                                `name`="mx", 
                                                `title`="$X$", 
                                                `superTitle`="Mean", 
                                                `type`="number"),
                                            list(
                                                `name`="my", 
                                                `title`="$Y$", 
                                                `superTitle`="Mean", 
                                                `type`="number"),
                                            list(
                                                `name`="xy", 
                                                `title`="$(X+Y)/2$", 
                                                `superTitle`="Mean", 
                                                `type`="number"),
                                            list(
                                                `name`="b", 
                                                `title`="$B=Y-X$", 
                                                `superTitle`="Mean", 
                                                `type`="number"),
                                            list(
                                                `name`="sdx", 
                                                `title`="$X$", 
                                                `superTitle`="Standard deviation", 
                                                `type`="number"),
                                            list(
                                                `name`="sdy", 
                                                `title`="$Y$", 
                                                `superTitle`="Standard deviation"))))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="c",
                                        title="*Conclusion:"))}))$new(options=options))
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                ppx = function() private$.items[["ppx"]],
                                ppy = function() private$.items[["ppy"]],
                                dp.b.c = function() private$.items[["dp.b.c"]],
                                c = function() private$.items[["c"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="v",
                                        title="Visualization of data")
                                    self$add(jmvcore::Image$new(
                                        options=options,
                                        name="ppx",
                                        title="Precision profile of clinical samples on measurement procedure X",
                                        width=550,
                                        height=350,
                                        renderFun=".pp.mp.render"))
                                    self$add(jmvcore::Image$new(
                                        options=options,
                                        name="ppy",
                                        title="Precision profile of clinical samples on measurement procedure Y",
                                        width=550,
                                        height=350,
                                        renderFun=".pp.mp.render"))
                                    self$add(jmvcore::Image$new(
                                        options=options,
                                        name="dp.b.c",
                                        title="Difference in measurement procedure X and measurement procedure Y for the same data vs mean of both measurement procedures",
                                        width=550,
                                        height=350,
                                        renderFun=".pp.mp.render"))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="c",
                                        title="*Conclusion:"))}))$new(options=options))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    note = function() private$.items[["note"]],
                    pex = function() private$.items[["pex"]],
                    pey = function() private$.items[["pey"]],
                    c = function() private$.items[["c"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="cvrm",
                            title="Components of variation within runs estimated from the reference material")
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="note"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="pex",
                            title="Position effect of reference material with measurement procedure X",
                            columns=list(
                                list(
                                    `name`="rmid", 
                                    `title`="ID", 
                                    `type`="text"),
                                list(
                                    `name`="mt", 
                                    `title`="$Mean_{Tot}$", 
                                    `type`="number"),
                                list(
                                    `name`="spm", 
                                    `title`="$s_{Pos-mean}$", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="$s_e$", 
                                    `type`="number"),
                                list(
                                    `name`="sp", 
                                    `title`="$s_{Pos}$", 
                                    `type`="number"),
                                list(
                                    `name`="F", 
                                    `title`="$F$", 
                                    `type`="number"),
                                list(
                                    `name`="pe", 
                                    `title`="Position<br>Effects", 
                                    `type`="text"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="pey",
                            title="Position effect of reference material with measurement procedure Y",
                            columns=list(
                                list(
                                    `name`="rmid", 
                                    `title`="ID", 
                                    `type`="text"),
                                list(
                                    `name`="mt", 
                                    `title`="$Mean_{Tot}$", 
                                    `type`="number"),
                                list(
                                    `name`="spm", 
                                    `title`="$s_{Pos-mean}$", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="$s_e$", 
                                    `type`="number"),
                                list(
                                    `name`="sp", 
                                    `title`="$s_{Pos}$", 
                                    `type`="number"),
                                list(
                                    `name`="F", 
                                    `title`="$F$", 
                                    `type`="number"),
                                list(
                                    `name`="pe", 
                                    `title`="Position<br>Effects", 
                                    `type`="text"))))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="c",
                            title="*Conclusion:"))}))$new(options=options))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cmp",
                title="Estimate differences between measurement procedures from the clinical samples"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="ttcs",
                title="Investigation of trends for clinical samples"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="tdcs",
                title="Test of differences ($\\sigma_d$) for CS"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="rma",
                title="ANOVA of RM results"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="sec",
                title="Summary of error components"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="seft",
                title="F-test of the hypothesis that $s_e$ is the same for CSs and RMs"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    r = function() private$.items[["r"]],
                    udrm = function() private$.items[["udrm"]],
                    adj = function() private$.items[["adj"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="adj",
                            title="CS MP x vs CS Bias: Ordinary Least Squares Regression Adjust")
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="r",
                            title="OLS Regression"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="udrm",
                            title="Expanded Uncertainty of $d_\\{RM\\}$"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="adj",
                            title="Adjusted Bias",
                            columns=list(
                                list(
                                    `name`="rmid", 
                                    `title`="RM ID", 
                                    `type`="text"),
                                list(
                                    `name`="x", 
                                    `title`="X", 
                                    `type`="number"),
                                list(
                                    `name`="y", 
                                    `title`="Y", 
                                    `type`="number"),
                                list(
                                    `name`="yl", 
                                    `title`="Y$_\\{Lower\\}$", 
                                    `type`="number"),
                                list(
                                    `name`="yu", 
                                    `title`="Y$_\\{Upper\\}$", 
                                    `type`="number"),
                                list(
                                    `name`="ay", 
                                    `title`="Adjusted Y", 
                                    `type`="number"),
                                list(
                                    `name`="ayl", 
                                    `title`="Adjusted Y$_\\{Lower\\}$", 
                                    `type`="number"),
                                list(
                                    `name`="ayu", 
                                    `title`="Adjusted Y$_\\{Upper\\}$", 
                                    `type`="number"))))}))$new(options=options))
            self$add(jmvcore::Table$new(
                options=options,
                name="ct",
                title="Commutability",
                columns=list(
                    list(
                        `name`="rmid", 
                        `type`="text", 
                        `title`="RM ID"),
                    list(
                        `name`="ym", 
                        `title`="$b$", 
                        `type`="number"),
                    list(
                        `name`="yl", 
                        `title`="$b_\\{Lower\\}$", 
                        `type`="number"),
                    list(
                        `name`="yu", 
                        `title`="$b_\\{Upper\\}$", 
                        `type`="number"),
                    list(
                        `name`="cl", 
                        `title`="$C_\\{Lower\\}$", 
                        `type`="number"),
                    list(
                        `name`="cu", 
                        `title`="$C_\\{Upper\\}$", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="Commutable?", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="ci",
                title="Commutability",
                width=550,
                height=300,
                renderFun=".ci.render"))}))

CommuntabilityEP30ABiasBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CommuntabilityEP30ABiasBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ReferenceMaterial",
                name = "CommuntabilityEP30ABias",
                version = c(1,0,0),
                options = options,
                results = CommuntabilityEP30ABiasResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Commutability (CLSI, EP30-A2-B)
#'
#' 
#' @param data .
#' @param csid .
#' @param csx .
#' @param csy .
#' @param rmid .
#' @param rmp .
#' @param rmx .
#' @param rmy .
#' @param ln .
#' @param logscale .
#' @param ef .
#' @param alpha .
#' @param g.alpha .
#' @param C .
#' @param mt .
#' @param unit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$mr} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$abb} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$symbols} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$descriptive$o} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$descriptive$mc} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$descriptive$v} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$cvrm$note} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cvrm$pex} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cvrm$pey} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cvrm$c} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cmp} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ttcs} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$tdcs} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$rma} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sec} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$seft} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$adj$r} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$adj$udrm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$adj$adj} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ct} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ci} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ct$asDF}
#'
#' \code{as.data.frame(results$ct)}
#'
#' @export
CommuntabilityEP30ABias <- function(
    data,
    csid,
    csx,
    csy,
    rmid,
    rmp,
    rmx,
    rmy,
    ln,
    logscale = TRUE,
    ef = 1.9,
    alpha = 0.05,
    g.alpha = 0.01,
    C = 12,
    mt = "HbA1c",
    unit = "mg/L") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("CommuntabilityEP30ABias requires jmvcore to be installed (restart may be required)")

    if ( ! missing(csid)) csid <- jmvcore::resolveQuo(jmvcore::enquo(csid))
    if ( ! missing(csx)) csx <- jmvcore::resolveQuo(jmvcore::enquo(csx))
    if ( ! missing(csy)) csy <- jmvcore::resolveQuo(jmvcore::enquo(csy))
    if ( ! missing(rmid)) rmid <- jmvcore::resolveQuo(jmvcore::enquo(rmid))
    if ( ! missing(rmp)) rmp <- jmvcore::resolveQuo(jmvcore::enquo(rmp))
    if ( ! missing(rmx)) rmx <- jmvcore::resolveQuo(jmvcore::enquo(rmx))
    if ( ! missing(rmy)) rmy <- jmvcore::resolveQuo(jmvcore::enquo(rmy))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(csid), csid, NULL),
            `if`( ! missing(csx), csx, NULL),
            `if`( ! missing(csy), csy, NULL),
            `if`( ! missing(rmid), rmid, NULL),
            `if`( ! missing(rmp), rmp, NULL),
            `if`( ! missing(rmx), rmx, NULL),
            `if`( ! missing(rmy), rmy, NULL))


    options <- CommuntabilityEP30ABiasOptions$new(
        csid = csid,
        csx = csx,
        csy = csy,
        rmid = rmid,
        rmp = rmp,
        rmx = rmx,
        rmy = rmy,
        ln = ln,
        logscale = logscale,
        ef = ef,
        alpha = alpha,
        g.alpha = g.alpha,
        C = C,
        mt = mt,
        unit = unit)

    analysis <- CommuntabilityEP30ABiasClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

