
# This file is automatically generated, you probably don't want to edit this

EstimatingBiasFromDifferencePlotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "EstimatingBiasFromDifferencePlotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            alpha = 0.05,
            ho = TRUE, ...) {

            super$initialize(
                package="ReferenceMaterial",
                name="EstimatingBiasFromDifferencePlot",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..ho <- jmvcore::OptionBool$new(
                "ho",
                ho,
                default=TRUE)

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..alpha)
            self$.addOption(private$..ho)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        alpha = function() private$..alpha$value,
        ho = function() private$..ho$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..alpha = NA,
        ..ho = NA)
)

EstimatingBiasFromDifferencePlotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "EstimatingBiasFromDifferencePlotResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        o = function() private$.items[["o"]],
        dp = function() private$.items[["dp"]],
        ddp = function() private$.items[["ddp"]],
        tt = function() private$.items[["tt"]],
        t = function() private$.items[["t"]],
        c = function() private$.items[["c"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Estimating Bias From Difference Plots")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Estimating Bias From Difference Plots",
                visible=FALSE))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    od = function() private$.items[["od"]],
                    opd = function() private$.items[["opd"]],
                    c = function() private$.items[["c"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="o",
                            title="Outliers")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="od",
                            title="Outliers of difference",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="x", 
                                    `title`="$x$", 
                                    `type`="number"),
                                list(
                                    `name`="y", 
                                    `title`="$y$", 
                                    `type`="number"),
                                list(
                                    `name`="b", 
                                    `title`="Bias", 
                                    `type`="number"),
                                list(
                                    `name`="mean", 
                                    `title`="$\\overline{\\text{Bias}}$", 
                                    `type`="number"),
                                list(
                                    `name`="esd", 
                                    `title`="$ESD$", 
                                    `type`="number"),
                                list(
                                    `name`="sd", 
                                    `title`="$SD$", 
                                    `type`="number"),
                                list(
                                    `name`="lambda", 
                                    `title`="$\\lambda$", 
                                    `type`="number")),
                            notes=list(
                                `n`="$ESD$: Extreme studentized deviate; $SD$: Standard deviation; $\\lambda$: Critical value.")))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="opd",
                            title="Outliers of percent difference",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="x", 
                                    `title`="$x$", 
                                    `type`="number"),
                                list(
                                    `name`="y", 
                                    `title`="$y$", 
                                    `type`="number"),
                                list(
                                    `name`="b", 
                                    `title`="Bias", 
                                    `type`="number"),
                                list(
                                    `name`="mean", 
                                    `title`="$\\overline{\\text{Bias}}$", 
                                    `type`="number"),
                                list(
                                    `name`="esd", 
                                    `title`="$ESD$", 
                                    `type`="number"),
                                list(
                                    `name`="sd", 
                                    `title`="$SD$", 
                                    `type`="number"),
                                list(
                                    `name`="lambda", 
                                    `title`="$\\lambda$", 
                                    `type`="number")),
                            notes=list(
                                `n`="$ESD$: Extreme studentized deviate; $SD$: Standard deviation; $\\lambda$: Critical value.")))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="c",
                            title="*Conclusion:"))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    d = function() private$.items[["d"]],
                    pd = function() private$.items[["pd"]],
                    c = function() private$.items[["c"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="dp",
                            title="Difference plots")
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="d",
                            title="Difference",
                            width=550,
                            height=400,
                            renderFun=".d.render"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="pd",
                            title="Percent difference",
                            width=550,
                            height=400,
                            renderFun=".d.render"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="c",
                            title="*Conclusion:"))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    dh = function() private$.items[["dh"]],
                    pdh = function() private$.items[["pdh"]],
                    c = function() private$.items[["c"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="ddp",
                            title="Distribution of differences")
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="dh",
                            title="Distribution of difference",
                            width=550,
                            height=400,
                            renderFun=".dh.render"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="pdh",
                            title="Distribution of percent difference",
                            width=550,
                            height=400,
                            renderFun=".dh.render"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="c",
                            title="*Conclusion:"))}))$new(options=options))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="tt",
                title="Confidence interval of difference"))
            self$add(jmvcore::Table$new(
                options=options,
                name="t",
                title="Bias",
                columns=list(
                    list(
                        `name`="t", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="cil", 
                        `superTitle`="CI (Mean)", 
                        `title`="Lower", 
                        `type`="number"),
                    list(
                        `name`="ciu", 
                        `superTitle`="CI (Mean)", 
                        `title`="Upper", 
                        `type`="number"),
                    list(
                        `name`="mid", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="cimidl", 
                        `superTitle`="CI (Median)", 
                        `type`="number", 
                        `title`="Lower"),
                    list(
                        `name`="cimidu", 
                        `superTitle`="CI (Median)", 
                        `type`="number", 
                        `title`="Upper"),
                    list(
                        `name`="tukey", 
                        `title`="HLE", 
                        `type`="number"),
                    list(
                        `name`="citukeyl", 
                        `superTitle`="CI (HLE)", 
                        `title`="Lower", 
                        `type`="number"),
                    list(
                        `name`="citukeyu", 
                        `superTitle`="CI (HLE)", 
                        `title`="Upper", 
                        `type`="number")),
                notes=list(
                    `n`="CI: Confidence interval; HLE: Hodges-Lehmann estimator; CI (HLE): Confidence interval of Hodges-Lehmann estimator, estimated using the Wilcoxon signed-rank method.")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="c",
                title="Conclusion"))}))

EstimatingBiasFromDifferencePlotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "EstimatingBiasFromDifferencePlotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ReferenceMaterial",
                name = "EstimatingBiasFromDifferencePlot",
                version = c(1,0,0),
                options = options,
                results = EstimatingBiasFromDifferencePlotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Estimating Bias From Difference Plots
#'
#' 
#' @param data .
#' @param x .
#' @param y .
#' @param alpha .
#' @param ho .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$o$od} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$o$opd} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$o$c} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$dp$d} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$dp$pd} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$dp$c} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ddp$dh} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ddp$pdh} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ddp$c} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$tt} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$t} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$c} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$t$asDF}
#'
#' \code{as.data.frame(results$t)}
#'
#' @export
EstimatingBiasFromDifferencePlot <- function(
    data,
    x,
    y,
    alpha = 0.05,
    ho = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("EstimatingBiasFromDifferencePlot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL))


    options <- EstimatingBiasFromDifferencePlotOptions$new(
        x = x,
        y = y,
        alpha = alpha,
        ho = ho)

    analysis <- EstimatingBiasFromDifferencePlotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

