
# This file is automatically generated, you probably don't want to edit this

FittingALineToScatterPlotsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FittingALineToScatterPlotsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            alpha = 0.05,
            ho = TRUE, ...) {

            super$initialize(
                package="ReferenceMaterial",
                name="FittingALineToScatterPlots",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..ho <- jmvcore::OptionBool$new(
                "ho",
                ho,
                default=TRUE)

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..alpha)
            self$.addOption(private$..ho)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        alpha = function() private$..alpha$value,
        ho = function() private$..ho$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..alpha = NA,
        ..ho = NA)
)

FittingALineToScatterPlotsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FittingALineToScatterPlotsResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        csd = function() private$.items[["csd"]],
        ccv = function() private$.items[["ccv"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Fitting a Line to Scatter Plots (Regression Analysis)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Fitting a Line to Scatter Plots (Regression Analysis)",
                visible=FALSE))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    ols = function() private$.items[["ols"]],
                    deming = function() private$.items[["deming"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="csd",
                            title="Constant standard deviation")
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                f = function() private$.items[["f"]],
                                c = function() private$.items[["c"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="ols",
                                        title="Ordinary linear regression fit")
                                    self$add(jmvcore::Image$new(
                                        options=options,
                                        name="f",
                                        title="Plot",
                                        width=550,
                                        height=400,
                                        renderFun=".r.render"))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="c",
                                        title="*Conclusion:"))}))$new(options=options))
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                f = function() private$.items[["f"]],
                                c = function() private$.items[["c"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="deming",
                                        title="Deming regression fit")
                                    self$add(jmvcore::Image$new(
                                        options=options,
                                        name="f",
                                        title="Plot",
                                        width=550,
                                        height=400,
                                        renderFun=".r.render"))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="c",
                                        title="*Conclusion:"))}))$new(options=options))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    wls = function() private$.items[["wls"]],
                    deming = function() private$.items[["deming"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="ccv",
                            title="Constant coefficient of variation")
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                f = function() private$.items[["f"]],
                                c = function() private$.items[["c"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="wls",
                                        title="Weighted ordinary linear regression fit")
                                    self$add(jmvcore::Image$new(
                                        options=options,
                                        name="f",
                                        title="Plot",
                                        width=550,
                                        height=400,
                                        renderFun=".r.render"))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="c",
                                        title="*Conclusion:"))}))$new(options=options))
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                f = function() private$.items[["f"]],
                                c = function() private$.items[["c"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="deming",
                                        title="Deming Regression Fit")
                                    self$add(jmvcore::Image$new(
                                        options=options,
                                        name="f",
                                        title="Plot",
                                        width=550,
                                        height=400,
                                        renderFun=".r.render"))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="c",
                                        title="*Conclusion:"))}))$new(options=options))}))$new(options=options))}))

FittingALineToScatterPlotsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FittingALineToScatterPlotsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ReferenceMaterial",
                name = "FittingALineToScatterPlots",
                version = c(1,0,0),
                options = options,
                results = FittingALineToScatterPlotsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Fitting a Line to Scatter Plots (Regression Analysis)
#'
#' 
#' @param data .
#' @param x .
#' @param y .
#' @param alpha .
#' @param ho .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$csd$ols} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$csd$deming} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$ccv$wls} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$ccv$deming} \tab \tab \tab \tab \tab a group \cr
#' }
#'
#' @export
FittingALineToScatterPlots <- function(
    data,
    x,
    y,
    alpha = 0.05,
    ho = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("FittingALineToScatterPlots requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL))


    options <- FittingALineToScatterPlotsOptions$new(
        x = x,
        y = y,
        alpha = alpha,
        ho = ho)

    analysis <- FittingALineToScatterPlotsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

