
# This file is automatically generated, you probably don't want to edit this

LinearityOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LinearityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            hs = 1,
            ls = 0,
            l = NULL,
            x = NULL,
            y = NULL,
            prc = NULL,
            rc = list(
                list(l=1, rc=0),
                list(l=2, rc=0.2),
                list(l=3, rc=0.4),
                list(l=4, rc=0.5),
                list(l=5, rc=0.6),
                list(l=6, rc=0.8),
                list(l=7, rc=1)),
            adl = 10,
            m = "HbA1c",
            unit = "%",
            ga = 0.01, ...) {

            super$initialize(
                package="ReferenceMaterial",
                name="Linearity",
                requiresData=TRUE,
                ...)

            private$..hs <- jmvcore::OptionNumber$new(
                "hs",
                hs,
                default=1)
            private$..ls <- jmvcore::OptionNumber$new(
                "ls",
                ls,
                default=0)
            private$..l <- jmvcore::OptionVariable$new(
                "l",
                l)
            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y)
            private$..prc <- jmvcore::OptionList$new(
                "prc",
                prc,
                options=list(
                    "5",
                    "6",
                    "7",
                    "8",
                    "11",
                    "12"))
            private$..rc <- jmvcore::OptionArray$new(
                "rc",
                rc,
                default=list(
                    list(l=1, rc=0),
                    list(l=2, rc=0.2),
                    list(l=3, rc=0.4),
                    list(l=4, rc=0.5),
                    list(l=5, rc=0.6),
                    list(l=6, rc=0.8),
                    list(l=7, rc=1)),
                template=jmvcore::OptionGroup$new(
                    "rc",
                    NULL,
                    elements=list(
                        jmvcore::OptionInteger$new(
                            "l",
                            NULL),
                        jmvcore::OptionNumber$new(
                            "rc",
                            NULL))))
            private$..adl <- jmvcore::OptionNumber$new(
                "adl",
                adl,
                default=10)
            private$..m <- jmvcore::OptionString$new(
                "m",
                m,
                default="HbA1c")
            private$..unit <- jmvcore::OptionString$new(
                "unit",
                unit,
                default="%")
            private$..ga <- jmvcore::OptionNumber$new(
                "ga",
                ga,
                default=0.01)

            self$.addOption(private$..hs)
            self$.addOption(private$..ls)
            self$.addOption(private$..l)
            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..prc)
            self$.addOption(private$..rc)
            self$.addOption(private$..adl)
            self$.addOption(private$..m)
            self$.addOption(private$..unit)
            self$.addOption(private$..ga)
        }),
    active = list(
        hs = function() private$..hs$value,
        ls = function() private$..ls$value,
        l = function() private$..l$value,
        x = function() private$..x$value,
        y = function() private$..y$value,
        prc = function() private$..prc$value,
        rc = function() private$..rc$value,
        adl = function() private$..adl$value,
        m = function() private$..m$value,
        unit = function() private$..unit$value,
        ga = function() private$..ga$value),
    private = list(
        ..hs = NA,
        ..ls = NA,
        ..l = NA,
        ..x = NA,
        ..y = NA,
        ..prc = NA,
        ..rc = NA,
        ..adl = NA,
        ..m = NA,
        ..unit = NA,
        ..ga = NA)
)

LinearityResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LinearityResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        abb = function() private$.items[["abb"]],
        m = function() private$.items[["m"]],
        mt = function() private$.items[["mt"]],
        d = function() private$.items[["d"]],
        r = function() private$.items[["r"]],
        c = function() private$.items[["c"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Linearity",
                refs=list(
                    "ep06a2"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Linearity",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="abb",
                title="Abbreviations",
                content="Where:\n<dl>\n<dt>MP$_X$:</dt><dd>Measurement procedure X</dd>\n<dt>MP$_Y$:</dt><dd>Measurement procedure Y</dd>\n<dt>$RC$:</dt><dd>Relative concentration</dd>\n<dt>$SD$:</dt><dd>Standard deviation</dd>\n<dt>$CV$:</dt><dd>Coefficient of variation</dd>\n</dl>\n"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="m",
                title="Mixing ratio between High- and Low-level samples"))
            self$add(jmvcore::Table$new(
                options=options,
                name="mt",
                title="Mixing ratio between High- and Low-level samples",
                columns=list(
                    list(
                        `name`="l", 
                        `title`="Level", 
                        `type`="integer"),
                    list(
                        `name`="rc", 
                        `title`="$RC$", 
                        `type`="number"),
                    list(
                        `name`="hr", 
                        `title`="High-level ratio (%)", 
                        `type`="number"),
                    list(
                        `name`="lr", 
                        `title`="Low-level ratio (%)", 
                        `type`="number"),
                    list(
                        `name`="e", 
                        `title`="Expected value", 
                        `type`="number"))))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    og = function() private$.items[["og"]],
                    mpx = function() private$.items[["mpx"]],
                    dtx = function() private$.items[["dtx"]],
                    mpy = function() private$.items[["mpy"]],
                    dty = function() private$.items[["dty"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="d",
                            title="Descriptive statistics")
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                o = function() private$.items[["o"]],
                                oc = function() private$.items[["oc"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="og",
                                        title="Outliers")
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="o",
                                        title="Outliers of measurements",
                                        visible=FALSE,
                                        columns=list(
                                            list(
                                                `name`="mp", 
                                                `title`="MP", 
                                                `type`="text"),
                                            list(
                                                `name`="l", 
                                                `title`="Level", 
                                                `type`="integer"),
                                            list(
                                                `name`="v", 
                                                `title`="Value", 
                                                `type`="number"))))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="oc",
                                        title="*Conclusion:"))}))$new(options=options))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="mpx",
                            title="Measurement procedure X"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="dtx",
                            title="Descriptive of measurement procedure X",
                            columns=list(
                                list(
                                    `name`="l", 
                                    `title`="Level", 
                                    `type`="integer"),
                                list(
                                    `name`="r", 
                                    `title`="Repetitions", 
                                    `type`="integer"),
                                list(
                                    `name`="m", 
                                    `title`="Mean", 
                                    `type`="number"),
                                list(
                                    `name`="sd", 
                                    `title`="$SD$", 
                                    `type`="number"),
                                list(
                                    `name`="cv", 
                                    `title`="$CV$ (%)", 
                                    `type`="number"),
                                list(
                                    `name`="var", 
                                    `title`="Variance", 
                                    `type`="number"),
                                list(
                                    `name`="w", 
                                    `title`="Weight"))))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="mpy",
                            title="Measurement procedure Y"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="dty",
                            title="Descriptive of measurement procedure Y",
                            columns=list(
                                list(
                                    `name`="l", 
                                    `title`="Level", 
                                    `type`="integer"),
                                list(
                                    `name`="r", 
                                    `title`="Repetitions", 
                                    `type`="integer"),
                                list(
                                    `name`="m", 
                                    `title`="Mean", 
                                    `type`="number"),
                                list(
                                    `name`="sd", 
                                    `title`="$SD$", 
                                    `type`="number"),
                                list(
                                    `name`="cv", 
                                    `title`="$CV$ (%)", 
                                    `type`="number"),
                                list(
                                    `name`="var", 
                                    `title`="Variance", 
                                    `type`="number"),
                                list(
                                    `name`="w", 
                                    `title`="Weight"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    mpx = function() private$.items[["mpx"]],
                    mpy = function() private$.items[["mpy"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="r",
                            title="Results")
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                f = function() private$.items[["f"]],
                                flx = function() private$.items[["flx"]],
                                t = function() private$.items[["t"]],
                                dlx = function() private$.items[["dlx"]],
                                rx = function() private$.items[["rx"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="mpx",
                                        title="Measurement procedure X")
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="f",
                                        title="Figure"))
                                    self$add(jmvcore::Image$new(
                                        options=options,
                                        name="flx",
                                        title="Linearity results on measurement procedure X",
                                        width=550,
                                        height=400,
                                        renderFun=".linearity.render"))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="t",
                                        title="Table"))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="dlx",
                                        title="Linearity results on measurement procedure X",
                                        columns=list(
                                            list(
                                                `name`="l", 
                                                `title`="Level", 
                                                `type`="integer"),
                                            list(
                                                `name`="e", 
                                                `title`="Expected<br>value", 
                                                `type`="number"),
                                            list(
                                                `name`="m", 
                                                `title`="Measured<br>value", 
                                                `type`="number"),
                                            list(
                                                `name`="p", 
                                                `title`="Predicted<br>value", 
                                                `type`="number"),
                                            list(
                                                `name`="d", 
                                                `title`="Deviation", 
                                                `type`="number"),
                                            list(
                                                `name`="dp", 
                                                `title`="Bias<br>(%)", 
                                                `type`="number"),
                                            list(
                                                `name`="result", 
                                                `title`="Linearity<br>", 
                                                `type`="text"))))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="rx",
                                        visible=FALSE))}))$new(options=options))
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                f = function() private$.items[["f"]],
                                fly = function() private$.items[["fly"]],
                                t = function() private$.items[["t"]],
                                dly = function() private$.items[["dly"]],
                                ry = function() private$.items[["ry"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="mpy",
                                        title="Measurement procedure Y")
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="f",
                                        title="Figure"))
                                    self$add(jmvcore::Image$new(
                                        options=options,
                                        name="fly",
                                        title="Linearity results on measurement procedure Y",
                                        width=550,
                                        height=400,
                                        renderFun=".linearity.render"))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="t",
                                        title="Table"))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="dly",
                                        title="Linearity results on measurement procedure Y",
                                        columns=list(
                                            list(
                                                `name`="l", 
                                                `title`="Level", 
                                                `type`="integer"),
                                            list(
                                                `name`="e", 
                                                `title`="Expected<br>value", 
                                                `type`="number"),
                                            list(
                                                `name`="m", 
                                                `title`="Measured<br>value", 
                                                `type`="number"),
                                            list(
                                                `name`="p", 
                                                `title`="Predicted<br>value", 
                                                `type`="number"),
                                            list(
                                                `name`="d", 
                                                `title`="Deviation", 
                                                `type`="number"),
                                            list(
                                                `name`="dp", 
                                                `title`="Bias<br>(%)", 
                                                `type`="number"),
                                            list(
                                                `name`="result", 
                                                `title`="Linearity<br>", 
                                                `type`="text"))))
                                    self$add(jmvcore::Preformatted$new(
                                        options=options,
                                        name="ry",
                                        visible=FALSE))}))$new(options=options))}))$new(options=options))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="c",
                title="Conclusion"))}))

LinearityBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LinearityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ReferenceMaterial",
                name = "Linearity",
                version = c(1,0,0),
                options = options,
                results = LinearityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Linearity
#'
#' 
#' @param data .
#' @param hs .
#' @param ls .
#' @param l .
#' @param x .
#' @param y .
#' @param prc .
#' @param rc .
#' @param adl .
#' @param m .
#' @param unit .
#' @param ga .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$abb} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$m} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$mt} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$d$og} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$d$mpx} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$d$dtx} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$d$mpy} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$d$dty} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$r$mpx} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$r$mpy} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$c} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$mt$asDF}
#'
#' \code{as.data.frame(results$mt)}
#'
#' @export
Linearity <- function(
    data,
    hs = 1,
    ls = 0,
    l,
    x,
    y,
    prc,
    rc = list(
                list(l=1, rc=0),
                list(l=2, rc=0.2),
                list(l=3, rc=0.4),
                list(l=4, rc=0.5),
                list(l=5, rc=0.6),
                list(l=6, rc=0.8),
                list(l=7, rc=1)),
    adl = 10,
    m = "HbA1c",
    unit = "%",
    ga = 0.01) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Linearity requires jmvcore to be installed (restart may be required)")

    if ( ! missing(l)) l <- jmvcore::resolveQuo(jmvcore::enquo(l))
    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(l), l, NULL),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL))


    options <- LinearityOptions$new(
        hs = hs,
        ls = ls,
        l = l,
        x = x,
        y = y,
        prc = prc,
        rc = rc,
        adl = adl,
        m = m,
        unit = unit,
        ga = ga)

    analysis <- LinearityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

