
# This file is automatically generated, you probably don't want to edit this

PrecisionEvaluationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PrecisionEvaluationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            hcx = NULL,
            hcy = NULL,
            lcx = NULL,
            lcy = NULL,
            ga = 0.01, ...) {

            super$initialize(
                package="ReferenceMaterial",
                name="PrecisionEvaluation",
                requiresData=TRUE,
                ...)

            private$..hcx <- jmvcore::OptionVariable$new(
                "hcx",
                hcx)
            private$..hcy <- jmvcore::OptionVariable$new(
                "hcy",
                hcy)
            private$..lcx <- jmvcore::OptionVariable$new(
                "lcx",
                lcx)
            private$..lcy <- jmvcore::OptionVariable$new(
                "lcy",
                lcy)
            private$..ga <- jmvcore::OptionNumber$new(
                "ga",
                ga,
                default=0.01)

            self$.addOption(private$..hcx)
            self$.addOption(private$..hcy)
            self$.addOption(private$..lcx)
            self$.addOption(private$..lcy)
            self$.addOption(private$..ga)
        }),
    active = list(
        hcx = function() private$..hcx$value,
        hcy = function() private$..hcy$value,
        lcx = function() private$..lcx$value,
        lcy = function() private$..lcy$value,
        ga = function() private$..ga$value),
    private = list(
        ..hcx = NA,
        ..hcy = NA,
        ..lcx = NA,
        ..lcy = NA,
        ..ga = NA)
)

PrecisionEvaluationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PrecisionEvaluationResults",
    inherit = jmvcore::Group,
    active = list(
        og = function() private$.items[["og"]],
        p = function() private$.items[["p"]],
        w = function() private$.items[["w"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Precision (Within-run)",
                refs=list(
                    "ep05a3"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    o = function() private$.items[["o"]],
                    oc = function() private$.items[["oc"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="og",
                            title="Outliers")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="o",
                            title="Outliers of measurements",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="mp", 
                                    `title`="MP", 
                                    `type`="text"),
                                list(
                                    `name`="l", 
                                    `title`="Sample level", 
                                    `type`="text"),
                                list(
                                    `name`="v", 
                                    `title`="Measurement", 
                                    `type`="number"))))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="oc",
                            title="*Conclusion:"))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    t = function() private$.items[["t"]],
                    a = function() private$.items[["a"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="p",
                            title="Precision")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="t",
                            title="Precision of difference measurement procedure",
                            columns=list(
                                list(
                                    `name`="mp", 
                                    `title`="MP", 
                                    `type`="text"),
                                list(
                                    `name`="lm", 
                                    `title`="Mean", 
                                    `type`="number", 
                                    `superTitle`="Low level sample"),
                                list(
                                    `name`="lsd", 
                                    `title`="$SD$", 
                                    `type`="number", 
                                    `superTitle`="Low level sample"),
                                list(
                                    `name`="lcv", 
                                    `title`="$CV$ (%)", 
                                    `type`="number", 
                                    `superTitle`="Low level sample"),
                                list(
                                    `name`="hm", 
                                    `title`="Mean", 
                                    `type`="number", 
                                    `superTitle`="High level sample"),
                                list(
                                    `name`="hsd", 
                                    `title`="$SD$", 
                                    `type`="number", 
                                    `superTitle`="High level sample"),
                                list(
                                    `name`="hcv", 
                                    `title`="$CV$ (%)", 
                                    `type`="number", 
                                    `superTitle`="High level sample"),
                                list(
                                    `name`="csd", 
                                    `title`="$SD$", 
                                    `type`="number", 
                                    `superTitle`="Combined"))))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="a"))}))$new(options=options))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="w",
                title="*Warning:",
                visible=FALSE))}))

PrecisionEvaluationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PrecisionEvaluationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ReferenceMaterial",
                name = "PrecisionEvaluation",
                version = c(1,0,0),
                options = options,
                results = PrecisionEvaluationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Precision (Within-run)
#'
#' 
#' @param data .
#' @param hcx .
#' @param hcy .
#' @param lcx .
#' @param lcy .
#' @param ga .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$og$o} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$og$oc} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$p$t} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$p$a} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$w} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
PrecisionEvaluation <- function(
    data,
    hcx,
    hcy,
    lcx,
    lcy,
    ga = 0.01) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("PrecisionEvaluation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(hcx)) hcx <- jmvcore::resolveQuo(jmvcore::enquo(hcx))
    if ( ! missing(hcy)) hcy <- jmvcore::resolveQuo(jmvcore::enquo(hcy))
    if ( ! missing(lcx)) lcx <- jmvcore::resolveQuo(jmvcore::enquo(lcx))
    if ( ! missing(lcy)) lcy <- jmvcore::resolveQuo(jmvcore::enquo(lcy))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(hcx), hcx, NULL),
            `if`( ! missing(hcy), hcy, NULL),
            `if`( ! missing(lcx), lcx, NULL),
            `if`( ! missing(lcy), lcy, NULL))


    options <- PrecisionEvaluationOptions$new(
        hcx = hcx,
        hcy = hcy,
        lcx = lcx,
        lcy = lcy,
        ga = ga)

    analysis <- PrecisionEvaluationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

