
# This file is automatically generated, you probably don't want to edit this

RandomSamplingOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RandomSamplingOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            csid = NULL,
            ratio = 33,
            sort = TRUE, ...) {

            super$initialize(
                package="ReferenceMaterial",
                name="RandomSampling",
                requiresData=TRUE,
                ...)

            private$..csid <- jmvcore::OptionVariable$new(
                "csid",
                csid)
            private$..ratio <- jmvcore::OptionNumber$new(
                "ratio",
                ratio,
                default=33)
            private$..sort <- jmvcore::OptionBool$new(
                "sort",
                sort,
                default=TRUE)

            self$.addOption(private$..csid)
            self$.addOption(private$..ratio)
            self$.addOption(private$..sort)
        }),
    active = list(
        csid = function() private$..csid$value,
        ratio = function() private$..ratio$value,
        sort = function() private$..sort$value),
    private = list(
        ..csid = NA,
        ..ratio = NA,
        ..sort = NA)
)

RandomSamplingResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RandomSamplingResults",
    inherit = jmvcore::Group,
    active = list(
        t = function() private$.items[["t"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Random Sampling")
            self$add(jmvcore::Table$new(
                options=options,
                name="t",
                title="Sampling Result",
                columns=list()))}))

RandomSamplingBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RandomSamplingBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ReferenceMaterial",
                name = "RandomSampling",
                version = c(1,0,0),
                options = options,
                results = RandomSamplingResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Random Sampling
#'
#' 
#' @param data .
#' @param csid .
#' @param ratio .
#' @param sort .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$t} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$t$asDF}
#'
#' \code{as.data.frame(results$t)}
#'
#' @export
RandomSampling <- function(
    data,
    csid,
    ratio = 33,
    sort = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("RandomSampling requires jmvcore to be installed (restart may be required)")

    if ( ! missing(csid)) csid <- jmvcore::resolveQuo(jmvcore::enquo(csid))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(csid), csid, NULL))


    options <- RandomSamplingOptions$new(
        csid = csid,
        ratio = ratio,
        sort = sort)

    analysis <- RandomSamplingClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

