
# This file is automatically generated, you probably don't want to edit this

RelativeEquivlenceOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RelativeEquivlenceOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            xcm1 = NULL,
            xcm2 = NULL,
            uxcm2 = NULL,
            ycm1 = NULL,
            ycm2 = NULL,
            k = 2, ...) {

            super$initialize(
                package="ReferenceMaterial",
                name="RelativeEquivlence",
                requiresData=TRUE,
                ...)

            private$..xcm1 <- jmvcore::OptionNumber$new(
                "xcm1",
                xcm1)
            private$..xcm2 <- jmvcore::OptionNumber$new(
                "xcm2",
                xcm2)
            private$..uxcm2 <- jmvcore::OptionNumber$new(
                "uxcm2",
                uxcm2)
            private$..ycm1 <- jmvcore::OptionVariables$new(
                "ycm1",
                ycm1)
            private$..ycm2 <- jmvcore::OptionVariables$new(
                "ycm2",
                ycm2)
            private$..k <- jmvcore::OptionNumber$new(
                "k",
                k,
                default=2)

            self$.addOption(private$..xcm1)
            self$.addOption(private$..xcm2)
            self$.addOption(private$..uxcm2)
            self$.addOption(private$..ycm1)
            self$.addOption(private$..ycm2)
            self$.addOption(private$..k)
        }),
    active = list(
        xcm1 = function() private$..xcm1$value,
        xcm2 = function() private$..xcm2$value,
        uxcm2 = function() private$..uxcm2$value,
        ycm1 = function() private$..ycm1$value,
        ycm2 = function() private$..ycm2$value,
        k = function() private$..k$value),
    private = list(
        ..xcm1 = NA,
        ..xcm2 = NA,
        ..uxcm2 = NA,
        ..ycm1 = NA,
        ..ycm2 = NA,
        ..k = NA)
)

RelativeEquivlenceResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RelativeEquivlenceResults",
    inherit = jmvcore::Group,
    active = list(
        tt = function() private$.items[["tt"]],
        t = function() private$.items[["t"]],
        text = function() private$.items[["text"]],
        c = function() private$.items[["c"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Relative Equivalence",
                refs=list(
                    "ectrc2019",
                    "iso17025",
                    "tsimillis2015"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="tt",
                title="Table"))
            self$add(jmvcore::Table$new(
                options=options,
                name="t",
                title="Relative equivalence of certified materials",
                columns=list(
                    list(
                        `name`="p1", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="v1", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="p2", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="v2", 
                        `title`="Value", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Calculation process parameters"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="c",
                title="Conclusion"))}))

RelativeEquivlenceBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RelativeEquivlenceBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ReferenceMaterial",
                name = "RelativeEquivlence",
                version = c(1,0,0),
                options = options,
                results = RelativeEquivlenceResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Relative Equivalence
#'
#' 
#' @param data .
#' @param xcm1 .
#' @param xcm2 .
#' @param uxcm2 .
#' @param ycm1 .
#' @param ycm2 .
#' @param k .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tt} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$t} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$c} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$t$asDF}
#'
#' \code{as.data.frame(results$t)}
#'
#' @export
RelativeEquivlence <- function(
    data,
    xcm1,
    xcm2,
    uxcm2,
    ycm1,
    ycm2,
    k = 2) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("RelativeEquivlence requires jmvcore to be installed (restart may be required)")

    if ( ! missing(ycm1)) ycm1 <- jmvcore::resolveQuo(jmvcore::enquo(ycm1))
    if ( ! missing(ycm2)) ycm2 <- jmvcore::resolveQuo(jmvcore::enquo(ycm2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(ycm1), ycm1, NULL),
            `if`( ! missing(ycm2), ycm2, NULL))


    options <- RelativeEquivlenceOptions$new(
        xcm1 = xcm1,
        xcm2 = xcm2,
        uxcm2 = uxcm2,
        ycm1 = ycm1,
        ycm2 = ycm2,
        k = k)

    analysis <- RelativeEquivlenceClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

