
# This file is automatically generated, you probably don't want to edit this

SampleSizeForISTOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeForISTOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            side = NULL,
            power = 0.2,
            alpha = 0.05,
            precision = 1,
            diff = 1.5, ...) {

            super$initialize(
                package="ReferenceMaterial",
                name="SampleSizeForIST",
                requiresData=TRUE,
                ...)

            private$..side <- jmvcore::OptionList$new(
                "side",
                side,
                options=list(
                    "o",
                    "t"))
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.2)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..precision <- jmvcore::OptionNumber$new(
                "precision",
                precision,
                default=1)
            private$..diff <- jmvcore::OptionNumber$new(
                "diff",
                diff,
                default=1.5)

            self$.addOption(private$..side)
            self$.addOption(private$..power)
            self$.addOption(private$..alpha)
            self$.addOption(private$..precision)
            self$.addOption(private$..diff)
        }),
    active = list(
        side = function() private$..side$value,
        power = function() private$..power$value,
        alpha = function() private$..alpha$value,
        precision = function() private$..precision$value,
        diff = function() private$..diff$value),
    private = list(
        ..side = NA,
        ..power = NA,
        ..alpha = NA,
        ..precision = NA,
        ..diff = NA)
)

SampleSizeForISTResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeForISTResults",
    inherit = jmvcore::Group,
    active = list(
        t = function() private$.items[["t"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Number of Replicates For Interference Screening Testing")
            self$add(jmvcore::Table$new(
                options=options,
                name="t",
                title="Number of replicates for interference screening testing",
                columns=list(
                    list(
                        `name`="t1", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="v1", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="t2", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="v2", 
                        `title`="Value", 
                        `type`="number")),
                notes=list(
                    `n`="$\\sigma$ is the assumed repeatability (within-run) standard deviation, $\\delta$ is the allowable difference between the means, $\\alpha$ is the 1 - confidence level, and $\\beta$ is the 1 - power.")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text"))}))

SampleSizeForISTBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeForISTBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ReferenceMaterial",
                name = "SampleSizeForIST",
                version = c(1,0,0),
                options = options,
                results = SampleSizeForISTResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Number of Replicates For Interference Screening Testing
#'
#' 
#' @param data .
#' @param side .
#' @param power .
#' @param alpha .
#' @param precision .
#' @param diff .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$t} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$t$asDF}
#'
#' \code{as.data.frame(results$t)}
#'
#' @export
SampleSizeForIST <- function(
    data,
    side,
    power = 0.2,
    alpha = 0.05,
    precision = 1,
    diff = 1.5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SampleSizeForIST requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- SampleSizeForISTOptions$new(
        side = side,
        power = power,
        alpha = alpha,
        precision = precision,
        diff = diff)

    analysis <- SampleSizeForISTClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

