
# This file is automatically generated, you probably don't want to edit this

SamplingOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SamplingOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            csid = NULL,
            cs = NULL,
            l = NULL,
            r = NULL,
            n = NULL,
            alpha = 0.05, ...) {

            super$initialize(
                package="ReferenceMaterial",
                name="Sampling",
                requiresData=TRUE,
                ...)

            private$..csid <- jmvcore::OptionVariable$new(
                "csid",
                csid)
            private$..cs <- jmvcore::OptionVariable$new(
                "cs",
                cs)
            private$..l <- jmvcore::OptionNumber$new(
                "l",
                l)
            private$..r <- jmvcore::OptionNumber$new(
                "r",
                r)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)

            self$.addOption(private$..csid)
            self$.addOption(private$..cs)
            self$.addOption(private$..l)
            self$.addOption(private$..r)
            self$.addOption(private$..n)
            self$.addOption(private$..alpha)
        }),
    active = list(
        csid = function() private$..csid$value,
        cs = function() private$..cs$value,
        l = function() private$..l$value,
        r = function() private$..r$value,
        n = function() private$..n$value,
        alpha = function() private$..alpha$value),
    private = list(
        ..csid = NA,
        ..cs = NA,
        ..l = NA,
        ..r = NA,
        ..n = NA,
        ..alpha = NA)
)

SamplingResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SamplingResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        sr = function() private$.items[["sr"]],
        ut = function() private$.items[["ut"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Uniform Sampling")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Uniform Sampling",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="sr",
                title="Sample Result",
                columns=list(
                    list(
                        `name`="no", 
                        `title`="No", 
                        `type`="integer"),
                    list(
                        `name`="lid", 
                        `superTitle`="Low", 
                        `title`="ID", 
                        `type`="text"),
                    list(
                        `name`="lv", 
                        `superTitle`="Low", 
                        `title`="Value", 
                        `type`="text"),
                    list(
                        `name`="mid", 
                        `superTitle`="Medium", 
                        `title`="ID", 
                        `type`="text"),
                    list(
                        `name`="mv", 
                        `superTitle`="Medium", 
                        `title`="Value", 
                        `type`="text"),
                    list(
                        `name`="hid", 
                        `superTitle`="High", 
                        `title`="ID", 
                        `type`="text"),
                    list(
                        `name`="hv", 
                        `superTitle`="High", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="ut",
                title="Uniform Test"))}))

SamplingBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SamplingBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ReferenceMaterial",
                name = "Sampling",
                version = c(1,0,0),
                options = options,
                results = SamplingResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Uniform Sampling
#'
#' 
#' @param data .
#' @param csid .
#' @param cs .
#' @param l .
#' @param r .
#' @param n .
#' @param alpha .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sr} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ut} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$sr$asDF}
#'
#' \code{as.data.frame(results$sr)}
#'
#' @export
Sampling <- function(
    data,
    csid,
    cs,
    l,
    r,
    n,
    alpha = 0.05) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Sampling requires jmvcore to be installed (restart may be required)")

    if ( ! missing(csid)) csid <- jmvcore::resolveQuo(jmvcore::enquo(csid))
    if ( ! missing(cs)) cs <- jmvcore::resolveQuo(jmvcore::enquo(cs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(csid), csid, NULL),
            `if`( ! missing(cs), cs, NULL))


    options <- SamplingOptions$new(
        csid = csid,
        cs = cs,
        l = l,
        r = r,
        n = n,
        alpha = alpha)

    analysis <- SamplingClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

