
# This file is automatically generated, you probably don't want to edit this

StabilityOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "StabilityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            alpha = 0.05, ...) {

            super$initialize(
                package="ReferenceMaterial",
                name="Stability",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariables$new(
                "y",
                y)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..alpha)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        alpha = function() private$..alpha$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..alpha = NA)
)

StabilityResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "StabilityResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        f = function() private$.items[["f"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Stability")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text"))
            self$add(jmvcore::Image$new(
                options=options,
                name="f",
                title="Stability regression",
                width=550,
                height=400,
                renderFun=".ols.render"))}))

StabilityBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "StabilityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ReferenceMaterial",
                name = "Stability",
                version = c(1,0,0),
                options = options,
                results = StabilityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Stability
#'
#' 
#' @param data .
#' @param x .
#' @param y .
#' @param alpha .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$f} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
Stability <- function(
    data,
    x,
    y,
    alpha = 0.05) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Stability requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL))


    options <- StabilityOptions$new(
        x = x,
        y = y,
        alpha = alpha)

    analysis <- StabilityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

