
# This file is automatically generated, you probably don't want to edit this

AppraisalRatioStudiesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "AppraisalRatioStudiesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            a = NULL,
            s = NULL,
            group = NULL,
            alpha = 0.05,
            coc = 15,
            tm = 5,
            iqr = NULL,
            iqrm = 3, ...) {

            super$initialize(
                package="Appraisal",
                name="AppraisalRatioStudies",
                requiresData=TRUE,
                ...)

            private$..a <- jmvcore::OptionVariable$new(
                "a",
                a)
            private$..s <- jmvcore::OptionVariable$new(
                "s",
                s)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..coc <- jmvcore::OptionNumber$new(
                "coc",
                coc,
                default=15)
            private$..tm <- jmvcore::OptionNumber$new(
                "tm",
                tm,
                default=5)
            private$..iqr <- jmvcore::OptionBool$new(
                "iqr",
                iqr)
            private$..iqrm <- jmvcore::OptionNumber$new(
                "iqrm",
                iqrm,
                default=3)

            self$.addOption(private$..a)
            self$.addOption(private$..s)
            self$.addOption(private$..group)
            self$.addOption(private$..alpha)
            self$.addOption(private$..coc)
            self$.addOption(private$..tm)
            self$.addOption(private$..iqr)
            self$.addOption(private$..iqrm)
        }),
    active = list(
        a = function() private$..a$value,
        s = function() private$..s$value,
        group = function() private$..group$value,
        alpha = function() private$..alpha$value,
        coc = function() private$..coc$value,
        tm = function() private$..tm$value,
        iqr = function() private$..iqr$value,
        iqrm = function() private$..iqrm$value),
    private = list(
        ..a = NA,
        ..s = NA,
        ..group = NA,
        ..alpha = NA,
        ..coc = NA,
        ..tm = NA,
        ..iqr = NA,
        ..iqrm = NA)
)

AppraisalRatioStudiesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "AppraisalRatioStudiesResults",
    inherit = jmvcore::Group,
    active = list(
        rr = function() private$.items[["rr"]],
        rss = function() private$.items[["rss"]],
        arss = function() private$.items[["arss"]],
        aspss = function() private$.items[["aspss"]],
        ci = function() private$.items[["ci"]],
        na = function() private$.items[["na"]],
        hetan = function() private$.items[["hetan"]],
        hetaev = function() private$.items[["hetaev"]],
        theg = function() private$.items[["theg"]],
        prbd = function() private$.items[["prbd"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Appraisal Ratio Studies")
            self$add(jmvcore::Table$new(
                options=options,
                name="rr",
                title="Removed Ratios",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="r", 
                        `title`="Row #", 
                        `type`="integer"),
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="rr", 
                        `title`="Removed Ratio", 
                        `type`="number"),
                    list(
                        `name`="reason", 
                        `title`="Reason", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rss",
                title="Ratio Summary Statistic",
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="integer"),
                    list(
                        `name`="median", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="wtd.mean", 
                        `title`="Wtd.Mean", 
                        `type`="number"),
                    list(
                        `name`="iqr", 
                        `title`="IQR", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="cod", 
                        `title`="COD", 
                        `type`="number"),
                    list(
                        `name`="cov", 
                        `title`="COV", 
                        `type`="number"),
                    list(
                        `name`="prd", 
                        `title`="PRD", 
                        `type`="number"),
                    list(
                        `name`="prb", 
                        `title`="PRB", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="arss",
                title="Additional Ratio Summary Statistics",
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="integer"),
                    list(
                        `name`="min", 
                        `title`="Min", 
                        `type`="number"),
                    list(
                        `name`="max", 
                        `title`="Max", 
                        `type`="number"),
                    list(
                        `name`="range", 
                        `title`="Range", 
                        `type`="number"),
                    list(
                        `name`="coc", 
                        `title`="COC", 
                        `type`="number"),
                    list(
                        `name`="wtd.cod", 
                        `title`="Wtd.COD", 
                        `type`="number"),
                    list(
                        `name`="wtd.cov", 
                        `title`="Wtd.COV", 
                        `type`="number"),
                    list(
                        `name`="madm", 
                        `title`="MADM", 
                        `type`="number"),
                    list(
                        `name`="mapdm", 
                        `title`="MADPM", 
                        `type`="number"),
                    list(
                        `name`="trim.mean", 
                        `title`="Trim.Mean", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="aspss",
                title="Appraisal and Sales Price Summary Statistics",
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="integer"),
                    list(
                        `name`="amean", 
                        `title`="Appraisal Mean", 
                        `type`="number"),
                    list(
                        `name`="spmean", 
                        `title`="Sale Price Mean", 
                        `type`="number"),
                    list(
                        `name`="amid", 
                        `title`="Appraisal Median", 
                        `type`="number"),
                    list(
                        `name`="spmid", 
                        `title`="Sale Price Median", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ci",
                title="Confidence Intervals",
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="integer"),
                    list(
                        `name`="rmid", 
                        `title`="Ratio<br>Median", 
                        `type`="number"),
                    list(
                        `name`="midl", 
                        `title`="Lower", 
                        `superTitle`="Median C.I.", 
                        `type`="number"),
                    list(
                        `name`="midr", 
                        `title`="Upper", 
                        `superTitle`="Median C.I.", 
                        `type`="number"),
                    list(
                        `name`="rmean", 
                        `title`="Ratio<br>Mean", 
                        `type`="number"),
                    list(
                        `name`="meanl", 
                        `title`="Lower", 
                        `superTitle`="Mean C.I.", 
                        `type`="number"),
                    list(
                        `name`="meanr", 
                        `title`="Upper", 
                        `superTitle`="Mean C.I.", 
                        `type`="number"),
                    list(
                        `name`="rwm", 
                        `title`="Ratio<br>Wtd.Mean", 
                        `type`="number"),
                    list(
                        `name`="wml", 
                        `title`="Lower", 
                        `superTitle`="Wtd.Mean C.I.", 
                        `type`="number"),
                    list(
                        `name`="wmr", 
                        `title`="Upper", 
                        `superTitle`="Wtd.Mean C.I.", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="na",
                title="Normality Assumption",
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="count", 
                        `title`="Count", 
                        `type`="integer"),
                    list(
                        `name`="skew", 
                        `title`="Skew", 
                        `type`="number"),
                    list(
                        `name`="kurt", 
                        `title`="Kurt", 
                        `type`="number"),
                    list(
                        `name`="sw", 
                        `title`="S-W", 
                        `superTitle`="P-Values", 
                        `type`="number"),
                    list(
                        `name`="ad", 
                        `title`="A-D", 
                        `superTitle`="P-Values", 
                        `type`="number"),
                    list(
                        `name`="mi", 
                        `title`="M-I", 
                        `superTitle`="P-Values", 
                        `type`="number"),
                    list(
                        `name`="ks", 
                        `title`="K-S", 
                        `superTitle`="P-Values", 
                        `type`="number"),
                    list(
                        `name`="ds", 
                        `title`="D-S", 
                        `superTitle`="P-Values", 
                        `type`="number"),
                    list(
                        `name`="dk", 
                        `title`="D-K", 
                        `superTitle`="P-Values", 
                        `type`="number"),
                    list(
                        `name`="do", 
                        `title`="D-O", 
                        `superTitle`="P-Values", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="hetan",
                title="Horizontal Equity Test Assumption: Normality",
                columns=list(
                    list(
                        `name`="na", 
                        `title`="Normality Attributes", 
                        `type`="text"),
                    list(
                        `name`="tv", 
                        `title`="Test Value", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="P-Value", 
                        `type`="number"),
                    list(
                        `name`="rn", 
                        `type`="text", 
                        `title`="Reject Normality? ($P\\lt \\alpha$)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="hetaev",
                title="Horizontal Equity Test Assumption: Equal Variance",
                columns=list(
                    list(
                        `name`="tn", 
                        `title`="Test Name", 
                        `type`="text"),
                    list(
                        `name`="tv", 
                        `title`="Test Value", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="P-Value", 
                        `type`="number"),
                    list(
                        `name`="rev", 
                        `title`="Reject Equal Variances? ($P\\lt \\alpha$)", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="theg",
                title="Tests of Horizontal Equity - Group",
                columns=list(
                    list(
                        `name`="tn", 
                        `title`="Test Name", 
                        `type`="text"),
                    list(
                        `name`="ts", 
                        `title`="Test Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="P-Value", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="Conclusion", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="prbd",
                title="Price-Related Bias (PRB) Details",
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="c", 
                        `title`="Count", 
                        `type`="integer"),
                    list(
                        `name`="pc", 
                        `title`="Pearson<br>Correlation", 
                        `type`="number"),
                    list(
                        `name`="prb", 
                        `title`="PRB<br>(Slope)", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Std<br>Error", 
                        `type`="number"),
                    list(
                        `name`="tv", 
                        `title`="T Value", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="PRB<br>(Slope)<br>Test<br>P-Value", 
                        `type`="number"),
                    list(
                        `name`="rve", 
                        `title`="Reject<br>Vertical<br>Equity?", 
                        `type`="text"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `superTitle`="C.I. of<br>PRB (Slope)", 
                        `type`="number"),
                    list(
                        `name`="cir", 
                        `title`="Upper", 
                        `superTitle`="C.I. of<br>PRB (Slope)", 
                        `type`="number"))))}))

AppraisalRatioStudiesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "AppraisalRatioStudiesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Appraisal",
                name = "AppraisalRatioStudies",
                version = c(1,0,0),
                options = options,
                results = AppraisalRatioStudiesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Appraisal Ratio Studies
#'
#' 
#' @param data .
#' @param a .
#' @param s .
#' @param group .
#' @param alpha .
#' @param coc .
#' @param tm .
#' @param iqr .
#' @param iqrm .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$rr} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rss} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$arss} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$aspss} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ci} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$na} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$hetan} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$hetaev} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$theg} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$prbd} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$rr$asDF}
#'
#' \code{as.data.frame(results$rr)}
#'
#' @export
AppraisalRatioStudies <- function(
    data,
    a,
    s,
    group,
    alpha = 0.05,
    coc = 15,
    tm = 5,
    iqr,
    iqrm = 3) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("AppraisalRatioStudies requires jmvcore to be installed (restart may be required)")

    if ( ! missing(a)) a <- jmvcore::resolveQuo(jmvcore::enquo(a))
    if ( ! missing(s)) s <- jmvcore::resolveQuo(jmvcore::enquo(s))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(a), a, NULL),
            `if`( ! missing(s), s, NULL),
            `if`( ! missing(group), group, NULL))


    options <- AppraisalRatioStudiesOptions$new(
        a = a,
        s = s,
        group = group,
        alpha = alpha,
        coc = coc,
        tm = tm,
        iqr = iqr,
        iqrm = iqrm)

    analysis <- AppraisalRatioStudiesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

