
# This file is automatically generated, you probably don't want to edit this

ClusteringInFamiliesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ClusteringInFamiliesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            A = NULL,
            a = "0.1", ...) {

            super$initialize(
                package="DiscreteDistribution",
                name="ClusteringInFamilies",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..A <- jmvcore::OptionVariable$new(
                "A",
                A)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.1"),
                default="0.1")

            self$.addOption(private$..x)
            self$.addOption(private$..A)
            self$.addOption(private$..a)
        }),
    active = list(
        x = function() private$..x$value,
        A = function() private$..A$value,
        a = function() private$..a$value),
    private = list(
        ..x = NA,
        ..A = NA,
        ..a = NA)
)

ClusteringInFamiliesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ClusteringInFamiliesResults",
    inherit = jmvcore::Group,
    active = list(
        h0 = function() private$.items[["h0"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Clustering In Families")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h0",
                title="$H_0$"))}))

ClusteringInFamiliesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ClusteringInFamiliesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiscreteDistribution",
                name = "ClusteringInFamilies",
                version = c(1,0,0),
                options = options,
                results = ClusteringInFamiliesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Clustering In Families
#'
#' 
#' @param data .
#' @param x .
#' @param A .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$h0} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
ClusteringInFamilies <- function(
    data,
    x,
    A,
    a = "0.1") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ClusteringInFamilies requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(A)) A <- jmvcore::resolveQuo(jmvcore::enquo(A))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(A), A, NULL))


    options <- ClusteringInFamiliesOptions$new(
        x = x,
        A = A,
        a = a)

    analysis <- ClusteringInFamiliesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

