
# This file is automatically generated, you probably don't want to edit this

GOFTPDOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GOFTPDOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            f = NULL,
            x = NULL,
            a = "0.05", ...) {

            super$initialize(
                package="DiscreteDistribution",
                name="GOFTPD",
                requiresData=TRUE,
                ...)

            private$..f <- jmvcore::OptionVariable$new(
                "f",
                f)
            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.1"),
                default="0.05")

            self$.addOption(private$..f)
            self$.addOption(private$..x)
            self$.addOption(private$..a)
        }),
    active = list(
        f = function() private$..f$value,
        x = function() private$..x$value,
        a = function() private$..a$value),
    private = list(
        ..f = NA,
        ..x = NA,
        ..a = NA)
)

GOFTPDResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GOFTPDResults",
    inherit = jmvcore::Group,
    active = list(
        goft = function() private$.items[["goft"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Goodness Of Fit Test(Poisson Distribution)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="goft",
                title="Goodness Of Fit Tests"))}))

GOFTPDBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GOFTPDBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiscreteDistribution",
                name = "GOFTPD",
                version = c(1,0,0),
                options = options,
                results = GOFTPDResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Goodness Of Fit Test(Poisson Distribution)
#'
#' 
#' @param data .
#' @param f .
#' @param x .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$goft} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
GOFTPD <- function(
    data,
    f,
    x,
    a = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("GOFTPD requires jmvcore to be installed (restart may be required)")

    if ( ! missing(f)) f <- jmvcore::resolveQuo(jmvcore::enquo(f))
    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(f), f, NULL),
            `if`( ! missing(x), x, NULL))


    options <- GOFTPDOptions$new(
        f = f,
        x = x,
        a = a)

    analysis <- GOFTPDClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

