
# This file is automatically generated, you probably don't want to edit this

GroupTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GroupTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            n = NULL,
            m = NULL,
            X = NULL, ...) {

            super$initialize(
                package="DiscreteDistribution",
                name="GroupTest",
                requiresData=TRUE,
                ...)

            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n)
            private$..m <- jmvcore::OptionInteger$new(
                "m",
                m)
            private$..X <- jmvcore::OptionInteger$new(
                "X",
                X)

            self$.addOption(private$..n)
            self$.addOption(private$..m)
            self$.addOption(private$..X)
        }),
    active = list(
        n = function() private$..n$value,
        m = function() private$..m$value,
        X = function() private$..X$value),
    private = list(
        ..n = NA,
        ..m = NA,
        ..X = NA)
)

GroupTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GroupTestResults",
    inherit = jmvcore::Group,
    active = list(
        P = function() private$.items[["P"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Group Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="P",
                title=""))}))

GroupTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GroupTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiscreteDistribution",
                name = "GroupTest",
                version = c(1,0,0),
                options = options,
                results = GroupTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Group Test
#'
#' 
#' @param data .
#' @param n .
#' @param m .
#' @param X .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$P} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
GroupTest <- function(
    data,
    n,
    m,
    X) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("GroupTest requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- GroupTestOptions$new(
        n = n,
        m = m,
        X = X)

    analysis <- GroupTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

