
# This file is automatically generated, you probably don't want to edit this

IEPPOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "IEPPOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            nam = NULL,
            n = NULL,
            x = NULL,
            a = "0.0250", ...) {

            super$initialize(
                package="DiscreteDistribution",
                name="IEPP",
                requiresData=TRUE,
                ...)

            private$..nam <- jmvcore::OptionBool$new(
                "nam",
                nam)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n)
            private$..x <- jmvcore::OptionInteger$new(
                "x",
                x)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.0050",
                    "0.0250",
                    "0.050"),
                default="0.0250")

            self$.addOption(private$..nam)
            self$.addOption(private$..n)
            self$.addOption(private$..x)
            self$.addOption(private$..a)
        }),
    active = list(
        nam = function() private$..nam$value,
        n = function() private$..n$value,
        x = function() private$..x$value,
        a = function() private$..a$value),
    private = list(
        ..nam = NA,
        ..n = NA,
        ..x = NA,
        ..a = NA)
)

IEPPResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "IEPPResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Interval Estimation of Population Proportion")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Interval Estimation of Population Proportion"))}))

IEPPBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "IEPPBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiscreteDistribution",
                name = "IEPP",
                version = c(1,0,0),
                options = options,
                results = IEPPResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Interval Estimation of Population Proportion
#'
#' 
#' @param data .
#' @param nam .
#' @param n .
#' @param x .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
IEPP <- function(
    data,
    nam,
    n,
    x,
    a = "0.0250") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("IEPP requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- IEPPOptions$new(
        nam = nam,
        n = n,
        x = x,
        a = a)

    analysis <- IEPPClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

