
# This file is automatically generated, you probably don't want to edit this

PEOfNBDOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PEOfNBDOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            f = NULL,
            x = NULL,
            method = NULL,
            sk = NULL,
            k1 = NULL,
            k2 = NULL,
            a = "0.05", ...) {

            super$initialize(
                package="DiscreteDistribution",
                name="PEOfNBD",
                requiresData=TRUE,
                ...)

            private$..f <- jmvcore::OptionVariable$new(
                "f",
                f)
            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "m",
                    "zf",
                    "ml"))
            private$..sk <- jmvcore::OptionBool$new(
                "sk",
                sk)
            private$..k1 <- jmvcore::OptionNumber$new(
                "k1",
                k1)
            private$..k2 <- jmvcore::OptionNumber$new(
                "k2",
                k2)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.1"),
                default="0.05")

            self$.addOption(private$..f)
            self$.addOption(private$..x)
            self$.addOption(private$..method)
            self$.addOption(private$..sk)
            self$.addOption(private$..k1)
            self$.addOption(private$..k2)
            self$.addOption(private$..a)
        }),
    active = list(
        f = function() private$..f$value,
        x = function() private$..x$value,
        method = function() private$..method$value,
        sk = function() private$..sk$value,
        k1 = function() private$..k1$value,
        k2 = function() private$..k2$value,
        a = function() private$..a$value),
    private = list(
        ..f = NA,
        ..x = NA,
        ..method = NA,
        ..sk = NA,
        ..k1 = NA,
        ..k2 = NA,
        ..a = NA)
)

PEOfNBDResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PEOfNBDResults",
    inherit = jmvcore::Group,
    active = list(
        result = function() private$.items[["result"]],
        goft = function() private$.items[["goft"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Parameter Estimation Of Negative Binomial Distribution")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="result",
                title=""))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="goft",
                title="Goodness Of Fit Tests"))}))

PEOfNBDBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PEOfNBDBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiscreteDistribution",
                name = "PEOfNBD",
                version = c(1,0,0),
                options = options,
                results = PEOfNBDResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Parameter Estimation Of Negative Binomial Distribution
#'
#' 
#' @param data .
#' @param f .
#' @param x .
#' @param method .
#' @param sk .
#' @param k1 .
#' @param k2 .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$result} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$goft} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
PEOfNBD <- function(
    data,
    f,
    x,
    method,
    sk,
    k1,
    k2,
    a = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("PEOfNBD requires jmvcore to be installed (restart may be required)")

    if ( ! missing(f)) f <- jmvcore::resolveQuo(jmvcore::enquo(f))
    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(f), f, NULL),
            `if`( ! missing(x), x, NULL))


    options <- PEOfNBDOptions$new(
        f = f,
        x = x,
        method = method,
        sk = sk,
        k1 = k1,
        k2 = k2,
        a = a)

    analysis <- PEOfNBDClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

