
# This file is automatically generated, you probably don't want to edit this

SMVSSMNBOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SMVSSMNBOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x1 = NULL,
            x2 = NULL,
            a = "0.0250", ...) {

            super$initialize(
                package="DiscreteDistribution",
                name="SMVSSMNB",
                requiresData=TRUE,
                ...)

            private$..x1 <- jmvcore::OptionVariable$new(
                "x1",
                x1)
            private$..x2 <- jmvcore::OptionVariable$new(
                "x2",
                x2)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.0050",
                    "0.0250",
                    "0.050"),
                default="0.0250")

            self$.addOption(private$..x1)
            self$.addOption(private$..x2)
            self$.addOption(private$..a)
        }),
    active = list(
        x1 = function() private$..x1$value,
        x2 = function() private$..x2$value,
        a = function() private$..a$value),
    private = list(
        ..x1 = NA,
        ..x2 = NA,
        ..a = NA)
)

SMVSSMNBResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SMVSSMNBResults",
    inherit = jmvcore::Group,
    active = list(
        h0 = function() private$.items[["h0"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample Mean VS Sample Mean(Negative Binomial)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h0",
                title=""))}))

SMVSSMNBBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SMVSSMNBBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiscreteDistribution",
                name = "SMVSSMNB",
                version = c(1,0,0),
                options = options,
                results = SMVSSMNBResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Sample Mean VS Sample Mean(Negative Binomial)
#'
#' 
#' @param data .
#' @param x1 .
#' @param x2 .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$h0} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
SMVSSMNB <- function(
    data,
    x1,
    x2,
    a = "0.0250") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SMVSSMNB requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x1)) x1 <- jmvcore::resolveQuo(jmvcore::enquo(x1))
    if ( ! missing(x2)) x2 <- jmvcore::resolveQuo(jmvcore::enquo(x2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x1), x1, NULL),
            `if`( ! missing(x2), x2, NULL))


    options <- SMVSSMNBOptions$new(
        x1 = x1,
        x2 = x2,
        a = a)

    analysis <- SMVSSMNBClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

