
# This file is automatically generated, you probably don't want to edit this

SMVSPMOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SMVSPMOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            nam = NULL,
            p = NULL,
            n = NULL,
            x = NULL,
            a = "0.05",
            h1 = NULL, ...) {

            super$initialize(
                package="DiscreteDistribution",
                name="SMVSPM",
                requiresData=TRUE,
                ...)

            private$..nam <- jmvcore::OptionBool$new(
                "nam",
                nam)
            private$..p <- jmvcore::OptionNumber$new(
                "p",
                p)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n)
            private$..x <- jmvcore::OptionInteger$new(
                "x",
                x)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.1"),
                default="0.05")
            private$..h1 <- jmvcore::OptionList$new(
                "h1",
                h1,
                options=list(
                    "gt",
                    "lt",
                    "neq"))

            self$.addOption(private$..nam)
            self$.addOption(private$..p)
            self$.addOption(private$..n)
            self$.addOption(private$..x)
            self$.addOption(private$..a)
            self$.addOption(private$..h1)
        }),
    active = list(
        nam = function() private$..nam$value,
        p = function() private$..p$value,
        n = function() private$..n$value,
        x = function() private$..x$value,
        a = function() private$..a$value,
        h1 = function() private$..h1$value),
    private = list(
        ..nam = NA,
        ..p = NA,
        ..n = NA,
        ..x = NA,
        ..a = NA,
        ..h1 = NA)
)

SMVSPMResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SMVSPMResults",
    inherit = jmvcore::Group,
    active = list(
        h0 = function() private$.items[["h0"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample Mean VS Population Mean")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h0",
                title=""))}))

SMVSPMBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SMVSPMBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiscreteDistribution",
                name = "SMVSPM",
                version = c(1,0,0),
                options = options,
                results = SMVSPMResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Sample Mean VS Population Mean
#'
#' 
#' @param data .
#' @param nam .
#' @param p .
#' @param n .
#' @param x .
#' @param a .
#' @param h1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$h0} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
SMVSPM <- function(
    data,
    nam,
    p,
    n,
    x,
    a = "0.05",
    h1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SMVSPM requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- SMVSPMOptions$new(
        nam = nam,
        p = p,
        n = n,
        x = x,
        a = a,
        h1 = h1)

    analysis <- SMVSPMClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

