
# This file is automatically generated, you probably don't want to edit this

SPVSSPOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SPVSSPOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x1 = NULL,
            x2 = NULL,
            n1 = NULL,
            n2 = NULL,
            a = "0.05",
            h1 = NULL, ...) {

            super$initialize(
                package="DiscreteDistribution",
                name="SPVSSP",
                requiresData=TRUE,
                ...)

            private$..x1 <- jmvcore::OptionNumber$new(
                "x1",
                x1)
            private$..x2 <- jmvcore::OptionNumber$new(
                "x2",
                x2)
            private$..n1 <- jmvcore::OptionNumber$new(
                "n1",
                n1)
            private$..n2 <- jmvcore::OptionNumber$new(
                "n2",
                n2)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.01",
                    "0.05",
                    "0.1"),
                default="0.05")
            private$..h1 <- jmvcore::OptionList$new(
                "h1",
                h1,
                options=list(
                    "gt",
                    "lt",
                    "neq"))

            self$.addOption(private$..x1)
            self$.addOption(private$..x2)
            self$.addOption(private$..n1)
            self$.addOption(private$..n2)
            self$.addOption(private$..a)
            self$.addOption(private$..h1)
        }),
    active = list(
        x1 = function() private$..x1$value,
        x2 = function() private$..x2$value,
        n1 = function() private$..n1$value,
        n2 = function() private$..n2$value,
        a = function() private$..a$value,
        h1 = function() private$..h1$value),
    private = list(
        ..x1 = NA,
        ..x2 = NA,
        ..n1 = NA,
        ..n2 = NA,
        ..a = NA,
        ..h1 = NA)
)

SPVSSPResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SPVSSPResults",
    inherit = jmvcore::Group,
    active = list(
        h0 = function() private$.items[["h0"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample Proportion VS Sample Proportion")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="h0",
                title=""))}))

SPVSSPBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SPVSSPBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DiscreteDistribution",
                name = "SPVSSP",
                version = c(1,0,0),
                options = options,
                results = SPVSSPResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Sample Proportion VS Sample Proportion
#'
#' 
#' @param data .
#' @param x1 .
#' @param x2 .
#' @param n1 .
#' @param n2 .
#' @param a .
#' @param h1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$h0} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
SPVSSP <- function(
    data,
    x1,
    x2,
    n1,
    n2,
    a = "0.05",
    h1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SPVSSP requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- SPVSSPOptions$new(
        x1 = x1,
        x2 = x2,
        n1 = n1,
        n2 = n2,
        a = a,
        h1 = h1)

    analysis <- SPVSSPClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

