
# This file is automatically generated, you probably don't want to edit this

ubbOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ubbOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL, ...) {

            super$initialize(
                package="YYT1709",
                name="ubb",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariables$new(
                "x",
                x)

            self$.addOption(private$..x)
        }),
    active = list(
        x = function() private$..x$value),
    private = list(
        ..x = NA)
)

ubbResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ubbResults",
    inherit = jmvcore::Group,
    active = list(
        table = function() private$.items[["table"]],
        result = function() private$.items[["result"]],
        ubb = function() private$.items[["ubb"]],
        detail = function() private$.items[["detail"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Measurement Uncertainty from Homogeneity")
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title=" ",
                rows=2,
                columns=list(
                    list(
                        `name`="source", 
                        `title`="Source of Variation", 
                        `type`="text"),
                    list(
                        `name`="SS", 
                        `title`="$SS$", 
                        `type`="number"),
                    list(
                        `name`="v", 
                        `title`="$\\nu$", 
                        `type`="integer"),
                    list(
                        `name`="MS", 
                        `title`="$MS$", 
                        `type`="number"),
                    list(
                        `name`="F", 
                        `title`="$F$", 
                        `type`="number"),
                    list(
                        `name`="F005vbbvwb", 
                        `title`="$F_\\{0.05(\\nu_\\{bb\\},\\nu_\\{wb\\})\\}$", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="result",
                title="Conclusion"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="ubb",
                title="$\\mu_\\{bb\\}$  ——Measurement uncertainty from between-bottle inhomogeneity"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    ni = function() private$.items[["ni"]],
                    xim = function() private$.items[["xim"]],
                    xmm = function() private$.items[["xmm"]],
                    N = function() private$.items[["N"]],
                    SSbb = function() private$.items[["SSbb"]],
                    SSwb = function() private$.items[["SSwb"]],
                    vbb = function() private$.items[["vbb"]],
                    vwb = function() private$.items[["vwb"]],
                    MSbb = function() private$.items[["MSbb"]],
                    MSwb = function() private$.items[["MSwb"]],
                    F = function() private$.items[["F"]],
                    F005vbbvwb = function() private$.items[["F005vbbvwb"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="detail",
                            title="Detailed Calculation")
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="ni",
                            title="$n_i$ — Number of replicate tests for bottle $i$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="xim",
                            title="$\\overline\\{x_i\\}$  ——Mean of tests for bottle $i$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="xmm",
                            title="$\\overline\\{\\overline\\{X\\}\\}$  ——Overall mean of tests across $m$ bottles"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="N",
                            title="$N$ — Total number of tests across $m$ bottles"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="SSbb",
                            title="$SS_\\{bb\\}$  ——Between-bottle sum of squares (ANOVA)"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="SSwb",
                            title="$SS_\\{wb\\}$  ——Within-bottle sum of squares (ANOVA)"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="vbb",
                            title="$\\nu_\\{bb\\}$  ——Between-bottle degrees of freedom"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="vwb",
                            title="$\\nu_\\{wb\\}$  ——Within-bottle degrees of freedom"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="MSbb",
                            title="$MS_\\{bb\\}$  ——Between-bottle mean square"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="MSwb",
                            title="$MS_\\{wb\\}$  ——Within-bottle mean square"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="F",
                            title="$F$ — Test statistic"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="F005vbbvwb",
                            title="$F_\\{0.05(\\nu_\\{bb\\},\\nu_\\{wb\\})\\}$  ——$F$-distribution variable at significance level 0.05"))}))$new(options=options))}))

ubbBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ubbBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "YYT1709",
                name = "ubb",
                version = c(1,0,0),
                options = options,
                results = ubbResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Measurement Uncertainty from Homogeneity
#'
#' 
#' @param data .
#' @param x .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$result} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ubb} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$ni} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$xim} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$xmm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$N} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$SSbb} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$SSwb} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$vbb} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$vwb} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$MSbb} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$MSwb} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$F} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$F005vbbvwb} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
ubb <- function(
    data,
    x) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ubb requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL))


    options <- ubbOptions$new(
        x = x)

    analysis <- ubbClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

