
# This file is automatically generated, you probably don't want to edit this

ucharOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ucharOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            Cwcal = NULL,
            Uwcal = NULL,
            k = NULL,
            Uorel = NULL,
            C = 1,
            x = NULL,
            single = TRUE,
            autow = NULL,
            w = NULL, ...) {

            super$initialize(
                package="YYT1709",
                name="uchar",
                requiresData=TRUE,
                ...)

            private$..Cwcal <- jmvcore::OptionNumber$new(
                "Cwcal",
                Cwcal)
            private$..Uwcal <- jmvcore::OptionNumber$new(
                "Uwcal",
                Uwcal)
            private$..k <- jmvcore::OptionNumber$new(
                "k",
                k)
            private$..Uorel <- jmvcore::OptionNumber$new(
                "Uorel",
                Uorel)
            private$..C <- jmvcore::OptionNumber$new(
                "C",
                C,
                default=1)
            private$..x <- jmvcore::OptionVariables$new(
                "x",
                x)
            private$..single <- jmvcore::OptionBool$new(
                "single",
                single,
                default=TRUE)
            private$..autow <- jmvcore::OptionBool$new(
                "autow",
                autow)
            private$..w <- jmvcore::OptionVariable$new(
                "w",
                w)

            self$.addOption(private$..Cwcal)
            self$.addOption(private$..Uwcal)
            self$.addOption(private$..k)
            self$.addOption(private$..Uorel)
            self$.addOption(private$..C)
            self$.addOption(private$..x)
            self$.addOption(private$..single)
            self$.addOption(private$..autow)
            self$.addOption(private$..w)
        }),
    active = list(
        Cwcal = function() private$..Cwcal$value,
        Uwcal = function() private$..Uwcal$value,
        k = function() private$..k$value,
        Uorel = function() private$..Uorel$value,
        C = function() private$..C$value,
        x = function() private$..x$value,
        single = function() private$..single$value,
        autow = function() private$..autow$value,
        w = function() private$..w$value),
    private = list(
        ..Cwcal = NA,
        ..Uwcal = NA,
        ..k = NA,
        ..Uorel = NA,
        ..C = NA,
        ..x = NA,
        ..single = NA,
        ..autow = NA,
        ..w = NA)
)

ucharResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ucharResults",
    inherit = jmvcore::Group,
    active = list(
        uchar = function() private$.items[["uchar"]],
        detail = function() private$.items[["detail"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Measurement Uncertainty from Characterization")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="uchar",
                title="$\\mu_\\{char\\}$  ——Standard uncertainty from calibrator value assignment"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    Xmm = function() private$.items[["Xmm"]],
                    Uwcalrel = function() private$.items[["Uwcalrel"]],
                    Ureprel = function() private$.items[["Ureprel"]],
                    Wi = function() private$.items[["Wi"]],
                    Ucharrel = function() private$.items[["Ucharrel"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="detail",
                            title="Detailed Calculation")
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="Xmm",
                            title="$\\overline\\{\\overline\\{X\\}\\}$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="Uwcalrel",
                            title="$\\mu_\\{wcal,rel\\}$  ——Relative uncertainty from working calibrator"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="Ureprel",
                            title="$\\mu_\\{REP,rel\\}$  ——Relative uncertainty from measurement imprecision"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="Wi",
                            title="$W_i \\propto \\frac\\{1\\}\\{(s_i/\\sqrt\\{n_i\\})^2\\}$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="Ucharrel",
                            title="$\\mu_\\{char,rel\\}$  ——Relative uncertainty from value assignment"))}))$new(options=options))}))

ucharBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ucharBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "YYT1709",
                name = "uchar",
                version = c(1,0,0),
                options = options,
                results = ucharResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Measurement Uncertainty from Characterization
#'
#' 
#' @param data .
#' @param Cwcal .
#' @param Uwcal .
#' @param k .
#' @param Uorel .
#' @param C .
#' @param x .
#' @param single .
#' @param autow .
#' @param w .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$uchar} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$Xmm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$Uwcalrel} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$Ureprel} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$Wi} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$Ucharrel} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
uchar <- function(
    data,
    Cwcal,
    Uwcal,
    k,
    Uorel,
    C = 1,
    x,
    single = TRUE,
    autow,
    w = NULL) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("uchar requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL))


    options <- ucharOptions$new(
        Cwcal = Cwcal,
        Uwcal = Uwcal,
        k = k,
        Uorel = Uorel,
        C = C,
        x = x,
        single = single,
        autow = autow,
        w = w)

    analysis <- ucharClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

