
# This file is automatically generated, you probably don't want to edit this

usOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "usOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            time = NULL,
            x = NULL, ...) {

            super$initialize(
                package="YYT1709",
                name="us",
                requiresData=TRUE,
                ...)

            private$..time <- jmvcore::OptionVariable$new(
                "time",
                time)
            private$..x <- jmvcore::OptionVariables$new(
                "x",
                x)

            self$.addOption(private$..time)
            self$.addOption(private$..x)
        }),
    active = list(
        time = function() private$..time$value,
        x = function() private$..x$value),
    private = list(
        ..time = NA,
        ..x = NA)
)

usResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "usResults",
    inherit = jmvcore::Group,
    active = list(
        table = function() private$.items[["table"]],
        result = function() private$.items[["result"]],
        detail = function() private$.items[["detail"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Measurement Uncertainty from Stability")
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title=" ",
                rows=1,
                columns=list(
                    list(
                        `name`="b1", 
                        `title`="$b_1$", 
                        `type`="number"),
                    list(
                        `name`="b0", 
                        `title`="$b_0$", 
                        `type`="number"),
                    list(
                        `name`="s", 
                        `title`="$s$", 
                        `type`="number"),
                    list(
                        `name`="sb1", 
                        `title`="$s(b_1)$", 
                        `type`="number"),
                    list(
                        `name`="tppf", 
                        `title`="$t_\\{0.05,n-2\\}$", 
                        `type`="number"),
                    list(
                        `name`="tppfsb1", 
                        `title`="$t_\\{0.05,n-2\\}\\cdot s(b_1)$", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="result",
                title="Conclusion"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    Xi = function() private$.items[["Xi"]],
                    Xm = function() private$.items[["Xm"]],
                    Yim = function() private$.items[["Yim"]],
                    Ymm = function() private$.items[["Ymm"]],
                    b1 = function() private$.items[["b1"]],
                    b0 = function() private$.items[["b0"]],
                    s = function() private$.items[["s"]],
                    sb1 = function() private$.items[["sb1"]],
                    tppf = function() private$.items[["tppf"]],
                    tppfsb1 = function() private$.items[["tppfsb1"]],
                    uts = function() private$.items[["uts"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="detail",
                            title="Detailed Calculation")
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="Xi",
                            title="$X_i$ — Time point $i$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="Xm",
                            title="$\\overline\\{X\\}$  ——Mean of all time points"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="Yim",
                            title="$\\overline\\{Y_i\\}$  ———Mean of test results at time point $i$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="Ymm",
                            title="$\\overline\\{\\overline\\{Y\\}\\}$  ———Overall mean of test results across all time points"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="b1",
                            title="$b_1=\\frac\\{\\sum_\\{i=1\\}^\\{n\\}(X_i-\\overline\\{X\\})(\\overline\\{Y_i\\}-\\overline\\{\\overline\\{Y\\}\\})\\}\\{\\sum_\\{i=1\\}^\\{n\\}(X_i-\\overline\\{X\\})^2\\}$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="b0",
                            title="$b_0=\\overline\\{\\overline\\{Y\\}\\}-b_1\\overline\\{X\\}$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="s",
                            title="$s=\\sqrt\\{\\frac\\{\\sum_\\{i=1\\}^\\{n\\}(\\overline\\{Y_i\\}-b_0-b_1X_i)^2\\}\\{n-2\\}\\}$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="sb1",
                            title="$s(b_1)$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="tppf",
                            title="$t_\\{0.05,n-2\\}$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="tppfsb1",
                            title="$t_\\{0.05,n-2\\}\\cdot s(b_1)$"))
                        self$add(jmvcore::Preformatted$new(
                            options=options,
                            name="uts",
                            title="$u_\\{ts\\}$  ——Uncertainty introduced by stability"))}))$new(options=options))}))

usBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "usBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "YYT1709",
                name = "us",
                version = c(1,0,0),
                options = options,
                results = usResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Measurement Uncertainty from Stability
#'
#' 
#' @param data .
#' @param time .
#' @param x .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$result} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$Xi} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$Xm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$Yim} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$Ymm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$b1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$b0} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$s} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$sb1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$tppf} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$tppfsb1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$detail$uts} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
us <- function(
    data,
    time,
    x) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("us requires jmvcore to be installed (restart may be required)")

    if ( ! missing(time)) time <- jmvcore::resolveQuo(jmvcore::enquo(time))
    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(time), time, NULL),
            `if`( ! missing(x), x, NULL))


    options <- usOptions$new(
        time = time,
        x = x)

    analysis <- usClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

