
# This file is automatically generated, you probably don't want to edit this

MinCrashOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MinCrashOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="MinCrash",
                name="MinCrash",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

MinCrashResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MinCrashResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        t = function() private$.items[["t"]],
        im = function() private$.items[["im"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="MinCrash")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="MinCrash"))
            self$add(jmvcore::Table$new(
                options=options,
                name="t",
                title="Table",
                columns=list(
                    list(
                        `name`="c1", 
                        `title`="c1", 
                        `type`="text"),
                    list(
                        `name`="c2", 
                        `title`="c2", 
                        `type`="text"),
                    list(
                        `name`="c3", 
                        `title`="c3", 
                        `type`="text"),
                    list(
                        `name`="c4", 
                        `title`="c4", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="im",
                title="Image",
                width=550,
                height=400,
                renderFun=".render"))}))

MinCrashBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MinCrashBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MinCrash",
                name = "MinCrash",
                version = c(1,0,0),
                options = options,
                results = MinCrashResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' MinCrash
#'
#' 
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$t} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$im} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$t$asDF}
#'
#' \code{as.data.frame(results$t)}
#'
#' @export
MinCrash <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("MinCrash requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- MinCrashOptions$new()

    analysis <- MinCrashClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

