
# This file is automatically generated, you probably don't want to edit this

CoefficientOfVariaitionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CoefficientOfVariaitionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mean = NULL,
            sd = NULL, ...) {

            super$initialize(
                package="Descriptive",
                name="CoefficientOfVariaition",
                requiresData=TRUE,
                ...)

            private$..mean <- jmvcore::OptionVariable$new(
                "mean",
                mean)
            private$..sd <- jmvcore::OptionVariable$new(
                "sd",
                sd)

            self$.addOption(private$..mean)
            self$.addOption(private$..sd)
        }),
    active = list(
        mean = function() private$..mean$value,
        sd = function() private$..sd$value),
    private = list(
        ..mean = NA,
        ..sd = NA)
)

CoefficientOfVariaitionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CoefficientOfVariaitionResults",
    inherit = jmvcore::Group,
    active = list(
        cvt = function() private$.items[["cvt"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="CV Using Mean And SD")
            self$add(jmvcore::Table$new(
                options=options,
                name="cvt",
                title="CV Using Mean And SD",
                columns=list(
                    list(
                        `name`="rn", 
                        `title`="RowNo", 
                        `type`="number"),
                    list(
                        `name`="cv", 
                        `title`="$CV(\\%)$", 
                        `type`="number"))))}))

CoefficientOfVariaitionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CoefficientOfVariaitionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Descriptive",
                name = "CoefficientOfVariaition",
                version = c(1,0,0),
                options = options,
                results = CoefficientOfVariaitionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' CV Using Mean And SD
#'
#' 
#' @param data .
#' @param mean .
#' @param sd .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$cvt} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$cvt$asDF}
#'
#' \code{as.data.frame(results$cvt)}
#'
#' @export
CoefficientOfVariaition <- function(
    data,
    mean,
    sd) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("CoefficientOfVariaition requires jmvcore to be installed (restart may be required)")

    if ( ! missing(mean)) mean <- jmvcore::resolveQuo(jmvcore::enquo(mean))
    if ( ! missing(sd)) sd <- jmvcore::resolveQuo(jmvcore::enquo(sd))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(mean), mean, NULL),
            `if`( ! missing(sd), sd, NULL))


    options <- CoefficientOfVariaitionOptions$new(
        mean = mean,
        sd = sd)

    analysis <- CoefficientOfVariaitionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

