
# This file is automatically generated, you probably don't want to edit this

DynamicSeriesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DynamicSeriesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            f = 0, ...) {

            super$initialize(
                package="Descriptive",
                name="DynamicSeries",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y)
            private$..f <- jmvcore::OptionNumber$new(
                "f",
                f,
                default=0)

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..f)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        f = function() private$..f$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..f = NA)
)

DynamicSeriesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DynamicSeriesResults",
    inherit = jmvcore::Group,
    active = list(
        dst = function() private$.items[["dst"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Dynamic Series")
            self$add(jmvcore::Table$new(
                options=options,
                name="dst",
                title="Dynamic Series Table",
                columns=list(
                    list(
                        `name`="x", 
                        `title`="X", 
                        `type`="number"),
                    list(
                        `name`="y", 
                        `title`="Y", 
                        `type`="number"),
                    list(
                        `name`="cag", 
                        `superTitle`="Absoulte Growth", 
                        `title`="Cumulative", 
                        `type`="number"),
                    list(
                        `name`="gag", 
                        `superTitle`="Absoulte Growth", 
                        `title`="Gradual", 
                        `type`="number"),
                    list(
                        `name`="bpdr", 
                        `superTitle`="Development Rate", 
                        `title`="Base-period", 
                        `type`="number"),
                    list(
                        `name`="sdr", 
                        `superTitle`="Development Rate", 
                        `title`="Sequential", 
                        `type`="number"),
                    list(
                        `name`="bpgr", 
                        `superTitle`="Growth Rate", 
                        `title`="Base-period", 
                        `type`="number"),
                    list(
                        `name`="sgr", 
                        `superTitle`="Growth Rate", 
                        `title`="Sequential", 
                        `type`="number"))))}))

DynamicSeriesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DynamicSeriesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Descriptive",
                name = "DynamicSeries",
                version = c(1,0,0),
                options = options,
                results = DynamicSeriesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Dynamic Series
#'
#' 
#' @param data .
#' @param x .
#' @param y .
#' @param f .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$dst} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$dst$asDF}
#'
#' \code{as.data.frame(results$dst)}
#'
#' @export
DynamicSeries <- function(
    data,
    x,
    y,
    f = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("DynamicSeries requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL))


    options <- DynamicSeriesOptions$new(
        x = x,
        y = y,
        f = f)

    analysis <- DynamicSeriesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

