
# This file is automatically generated, you probably don't want to edit this

GeometricMeanDirectOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GeometricMeanDirectOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            X = NULL, ...) {

            super$initialize(
                package="Descriptive",
                name="GeometricMeanDirect",
                requiresData=TRUE,
                ...)

            private$..X <- jmvcore::OptionVariables$new(
                "X",
                X)

            self$.addOption(private$..X)
        }),
    active = list(
        X = function() private$..X$value),
    private = list(
        ..X = NA)
)

GeometricMeanDirectResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GeometricMeanDirectResults",
    inherit = jmvcore::Group,
    active = list(
        gmean = function() private$.items[["gmean"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Geometric Mean(Direct Method)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="gmean",
                title="$G=lg^\\{-1\\}(\\frac\\{\\sum lg X\\}\\{n\\})$"))}))

GeometricMeanDirectBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GeometricMeanDirectBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Descriptive",
                name = "GeometricMeanDirect",
                version = c(1,0,0),
                options = options,
                results = GeometricMeanDirectResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Geometric Mean(Direct Method)
#'
#' 
#' @param data .
#' @param X .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$gmean} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
GeometricMeanDirect <- function(
    data,
    X) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("GeometricMeanDirect requires jmvcore to be installed (restart may be required)")

    if ( ! missing(X)) X <- jmvcore::resolveQuo(jmvcore::enquo(X))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(X), X, NULL))


    options <- GeometricMeanDirectOptions$new(
        X = X)

    analysis <- GeometricMeanDirectClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

