
# This file is automatically generated, you probably don't want to edit this

GeometricMeanFrequencyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GeometricMeanFrequencyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            f = NULL,
            X = NULL, ...) {

            super$initialize(
                package="Descriptive",
                name="GeometricMeanFrequency",
                requiresData=TRUE,
                ...)

            private$..f <- jmvcore::OptionVariable$new(
                "f",
                f)
            private$..X <- jmvcore::OptionVariable$new(
                "X",
                X)

            self$.addOption(private$..f)
            self$.addOption(private$..X)
        }),
    active = list(
        f = function() private$..f$value,
        X = function() private$..X$value),
    private = list(
        ..f = NA,
        ..X = NA)
)

GeometricMeanFrequencyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GeometricMeanFrequencyResults",
    inherit = jmvcore::Group,
    active = list(
        gmean = function() private$.items[["gmean"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Geometric Mean(Frequency Table Method)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="gmean",
                title="$G=\\lg^\\{-1\\}(\\frac\\{\\sum f \\lg X\\}\\{\\sum f\\})$"))}))

GeometricMeanFrequencyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GeometricMeanFrequencyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Descriptive",
                name = "GeometricMeanFrequency",
                version = c(1,0,0),
                options = options,
                results = GeometricMeanFrequencyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Geometric Mean(Frequency Table Method)
#'
#' 
#' @param data .
#' @param f .
#' @param X .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$gmean} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
GeometricMeanFrequency <- function(
    data,
    f,
    X) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("GeometricMeanFrequency requires jmvcore to be installed (restart may be required)")

    if ( ! missing(f)) f <- jmvcore::resolveQuo(jmvcore::enquo(f))
    if ( ! missing(X)) X <- jmvcore::resolveQuo(jmvcore::enquo(X))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(f), f, NULL),
            `if`( ! missing(X), X, NULL))


    options <- GeometricMeanFrequencyOptions$new(
        f = f,
        X = X)

    analysis <- GeometricMeanFrequencyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

