
# This file is automatically generated, you probably don't want to edit this

MedianFrequencyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MedianFrequencyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            X = NULL,
            f = NULL, ...) {

            super$initialize(
                package="Descriptive",
                name="MedianFrequency",
                requiresData=TRUE,
                ...)

            private$..X <- jmvcore::OptionVariable$new(
                "X",
                X)
            private$..f <- jmvcore::OptionVariable$new(
                "f",
                f)

            self$.addOption(private$..X)
            self$.addOption(private$..f)
        }),
    active = list(
        X = function() private$..X$value,
        f = function() private$..f$value),
    private = list(
        ..X = NA,
        ..f = NA)
)

MedianFrequencyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MedianFrequencyResults",
    inherit = jmvcore::Group,
    active = list(
        median = function() private$.items[["median"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Median (Frequency)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="median",
                title="$M$"))}))

MedianFrequencyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MedianFrequencyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Descriptive",
                name = "MedianFrequency",
                version = c(1,0,0),
                options = options,
                results = MedianFrequencyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Median (Frequency)
#'
#' 
#' @param data .
#' @param X .
#' @param f .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$median} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
MedianFrequency <- function(
    data,
    X,
    f) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("MedianFrequency requires jmvcore to be installed (restart may be required)")

    if ( ! missing(X)) X <- jmvcore::resolveQuo(jmvcore::enquo(X))
    if ( ! missing(f)) f <- jmvcore::resolveQuo(jmvcore::enquo(f))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(X), X, NULL),
            `if`( ! missing(f), f, NULL))


    options <- MedianFrequencyOptions$new(
        X = X,
        f = f)

    analysis <- MedianFrequencyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

