
# This file is automatically generated, you probably don't want to edit this

PercentileFrequencyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PercentileFrequencyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            l = NULL,
            i = NULL,
            f = NULL,
            X = 0,
            qr = NULL, ...) {

            super$initialize(
                package="Descriptive",
                name="PercentileFrequency",
                requiresData=TRUE,
                ...)

            private$..l <- jmvcore::OptionVariable$new(
                "l",
                l)
            private$..i <- jmvcore::OptionVariable$new(
                "i",
                i)
            private$..f <- jmvcore::OptionVariable$new(
                "f",
                f)
            private$..X <- jmvcore::OptionNumber$new(
                "X",
                X,
                default=0)
            private$..qr <- jmvcore::OptionBool$new(
                "qr",
                qr)

            self$.addOption(private$..l)
            self$.addOption(private$..i)
            self$.addOption(private$..f)
            self$.addOption(private$..X)
            self$.addOption(private$..qr)
        }),
    active = list(
        l = function() private$..l$value,
        i = function() private$..i$value,
        f = function() private$..f$value,
        X = function() private$..X$value,
        qr = function() private$..qr$value),
    private = list(
        ..l = NA,
        ..i = NA,
        ..f = NA,
        ..X = NA,
        ..qr = NA)
)

PercentileFrequencyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PercentileFrequencyResults",
    inherit = jmvcore::Group,
    active = list(
        sp = function() private$.items[["sp"]],
        qr = function() private$.items[["qr"]],
        pt = function() private$.items[["pt"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Percentile(Frequency Table Method)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="sp",
                title=""))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="qr",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="pt",
                title="Percentile Table",
                columns=list(
                    list(
                        `name`="x", 
                        `title`="$X$", 
                        `type`="text"),
                    list(
                        `name`="px", 
                        `title`="$P_X$", 
                        `type`="number"))))}))

PercentileFrequencyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PercentileFrequencyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Descriptive",
                name = "PercentileFrequency",
                version = c(1,0,0),
                options = options,
                results = PercentileFrequencyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Percentile(Frequency Table Method)
#'
#' 
#' @param data .
#' @param l .
#' @param i .
#' @param f .
#' @param X .
#' @param qr .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$sp} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$qr} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$pt} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pt$asDF}
#'
#' \code{as.data.frame(results$pt)}
#'
#' @export
PercentileFrequency <- function(
    data,
    l,
    i,
    f,
    X = 0,
    qr) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("PercentileFrequency requires jmvcore to be installed (restart may be required)")

    if ( ! missing(l)) l <- jmvcore::resolveQuo(jmvcore::enquo(l))
    if ( ! missing(i)) i <- jmvcore::resolveQuo(jmvcore::enquo(i))
    if ( ! missing(f)) f <- jmvcore::resolveQuo(jmvcore::enquo(f))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(l), l, NULL),
            `if`( ! missing(i), i, NULL),
            `if`( ! missing(f), f, NULL))


    options <- PercentileFrequencyOptions$new(
        l = l,
        i = i,
        f = f,
        X = X,
        qr = qr)

    analysis <- PercentileFrequencyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

