
# This file is automatically generated, you probably don't want to edit this

PercentileDirectOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PercentileDirectOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            X = NULL,
            sp = 0, ...) {

            super$initialize(
                package="Descriptive",
                name="PercentileDirect",
                requiresData=TRUE,
                ...)

            private$..X <- jmvcore::OptionVariables$new(
                "X",
                X)
            private$..sp <- jmvcore::OptionNumber$new(
                "sp",
                sp,
                default=0)

            self$.addOption(private$..X)
            self$.addOption(private$..sp)
        }),
    active = list(
        X = function() private$..X$value,
        sp = function() private$..sp$value),
    private = list(
        ..X = NA,
        ..sp = NA)
)

PercentileDirectResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PercentileDirectResults",
    inherit = jmvcore::Group,
    active = list(
        px = function() private$.items[["px"]],
        pt = function() private$.items[["pt"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Percentile(Direct Method)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="px",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="pt",
                title="Percentile Table",
                columns=list(
                    list(
                        `name`="x", 
                        `title`="$X$", 
                        `type`="text"),
                    list(
                        `name`="px", 
                        `title`="$P_X$", 
                        `type`="number"))))}))

PercentileDirectBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "PercentileDirectBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Descriptive",
                name = "PercentileDirect",
                version = c(1,0,0),
                options = options,
                results = PercentileDirectResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Percentile(Direct Method)
#'
#' 
#' @param data .
#' @param X .
#' @param sp .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$px} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$pt} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pt$asDF}
#'
#' \code{as.data.frame(results$pt)}
#'
#' @export
PercentileDirect <- function(
    data,
    X,
    sp = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("PercentileDirect requires jmvcore to be installed (restart may be required)")

    if ( ! missing(X)) X <- jmvcore::resolveQuo(jmvcore::enquo(X))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(X), X, NULL))


    options <- PercentileDirectOptions$new(
        X = X,
        sp = sp)

    analysis <- PercentileDirectClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

