
# This file is automatically generated, you probably don't want to edit this

ReferenceRangeNDOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ReferenceRangeNDOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mean = NULL,
            sd = NULL,
            rr = "95",
            side = "ts", ...) {

            super$initialize(
                package="Descriptive",
                name="ReferenceRangeND",
                requiresData=TRUE,
                ...)

            private$..mean <- jmvcore::OptionVariable$new(
                "mean",
                mean)
            private$..sd <- jmvcore::OptionVariable$new(
                "sd",
                sd)
            private$..rr <- jmvcore::OptionList$new(
                "rr",
                rr,
                default="95",
                options=list(
                    "99",
                    "95",
                    "90",
                    "80"))
            private$..side <- jmvcore::OptionList$new(
                "side",
                side,
                options=list(
                    "os",
                    "ts"),
                default="ts")

            self$.addOption(private$..mean)
            self$.addOption(private$..sd)
            self$.addOption(private$..rr)
            self$.addOption(private$..side)
        }),
    active = list(
        mean = function() private$..mean$value,
        sd = function() private$..sd$value,
        rr = function() private$..rr$value,
        side = function() private$..side$value),
    private = list(
        ..mean = NA,
        ..sd = NA,
        ..rr = NA,
        ..side = NA)
)

ReferenceRangeNDResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ReferenceRangeNDResults",
    inherit = jmvcore::Group,
    active = list(
        rrt = function() private$.items[["rrt"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Reference Range(Normal Distribution Method)")
            self$add(jmvcore::Table$new(
                options=options,
                name="rrt",
                title="Reference Range Table",
                columns=list(
                    list(
                        `name`="rn", 
                        `title`="RowNo", 
                        `type`="number"),
                    list(
                        `name`="u", 
                        `title`="$u$", 
                        `type`="number"),
                    list(
                        `name`="nu", 
                        `title`="$\\overline\\{X\\} - uS$", 
                        `type`="number"),
                    list(
                        `name`="pu", 
                        `title`="$\\overline\\{X\\} + uS$", 
                        `type`="number"))))}))

ReferenceRangeNDBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ReferenceRangeNDBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Descriptive",
                name = "ReferenceRangeND",
                version = c(1,0,0),
                options = options,
                results = ReferenceRangeNDResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Reference Range(Normal Distribution Method)
#'
#' 
#' @param data .
#' @param mean .
#' @param sd .
#' @param rr .
#' @param side .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$rrt} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$rrt$asDF}
#'
#' \code{as.data.frame(results$rrt)}
#'
#' @export
ReferenceRangeND <- function(
    data,
    mean,
    sd,
    rr = "95",
    side = "ts") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ReferenceRangeND requires jmvcore to be installed (restart may be required)")

    if ( ! missing(mean)) mean <- jmvcore::resolveQuo(jmvcore::enquo(mean))
    if ( ! missing(sd)) sd <- jmvcore::resolveQuo(jmvcore::enquo(sd))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(mean), mean, NULL),
            `if`( ! missing(sd), sd, NULL))


    options <- ReferenceRangeNDOptions$new(
        mean = mean,
        sd = sd,
        rr = rr,
        side = side)

    analysis <- ReferenceRangeNDClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

