
# This file is automatically generated, you probably don't want to edit this

SampleSizeCategoricalOneSampleOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeCategoricalOneSampleOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            p0 = NULL,
            p1 = NULL,
            aer = "0.05",
            ber = "0.05", ...) {

            super$initialize(
                package="Descriptive",
                name="SampleSizeCategoricalOneSample",
                requiresData=TRUE,
                ...)

            private$..p0 <- jmvcore::OptionNumber$new(
                "p0",
                p0)
            private$..p1 <- jmvcore::OptionNumber$new(
                "p1",
                p1)
            private$..aer <- jmvcore::OptionList$new(
                "aer",
                aer,
                options=list(
                    "0.005",
                    "0.01",
                    "0.025",
                    "0.05",
                    "0.0050",
                    "0.010",
                    "0.0250",
                    "0.050"),
                default="0.05")
            private$..ber <- jmvcore::OptionList$new(
                "ber",
                ber,
                options=list(
                    "0.01",
                    "0.05",
                    "0.10",
                    "0.20",
                    "0.5"),
                default="0.05")

            self$.addOption(private$..p0)
            self$.addOption(private$..p1)
            self$.addOption(private$..aer)
            self$.addOption(private$..ber)
        }),
    active = list(
        p0 = function() private$..p0$value,
        p1 = function() private$..p1$value,
        aer = function() private$..aer$value,
        ber = function() private$..ber$value),
    private = list(
        ..p0 = NA,
        ..p1 = NA,
        ..aer = NA,
        ..ber = NA)
)

SampleSizeCategoricalOneSampleResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeCategoricalOneSampleResults",
    inherit = jmvcore::Group,
    active = list(
        n = function() private$.items[["n"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample Size(Categorical One Sample)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="n",
                title="Sample Size(Categorical One Sample)"))}))

SampleSizeCategoricalOneSampleBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeCategoricalOneSampleBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Descriptive",
                name = "SampleSizeCategoricalOneSample",
                version = c(1,0,0),
                options = options,
                results = SampleSizeCategoricalOneSampleResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Sample Size(Categorical One Sample)
#'
#' 
#' @param data .
#' @param p0 .
#' @param p1 .
#' @param aer .
#' @param ber .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$n} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
SampleSizeCategoricalOneSample <- function(
    data,
    p0,
    p1,
    aer = "0.05",
    ber = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SampleSizeCategoricalOneSample requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- SampleSizeCategoricalOneSampleOptions$new(
        p0 = p0,
        p1 = p1,
        aer = aer,
        ber = ber)

    analysis <- SampleSizeCategoricalOneSampleClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

