
# This file is automatically generated, you probably don't want to edit this

SampleSizeCategoricalTIGOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeCategoricalTIGOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pc = NULL,
            pe = NULL,
            aer = "0.05",
            ber = "0.05", ...) {

            super$initialize(
                package="Descriptive",
                name="SampleSizeCategoricalTIG",
                requiresData=TRUE,
                ...)

            private$..pc <- jmvcore::OptionNumber$new(
                "pc",
                pc)
            private$..pe <- jmvcore::OptionNumber$new(
                "pe",
                pe)
            private$..aer <- jmvcore::OptionList$new(
                "aer",
                aer,
                options=list(
                    "0.005",
                    "0.01",
                    "0.025",
                    "0.05",
                    "0.0050",
                    "0.010",
                    "0.0250",
                    "0.050"),
                default="0.05")
            private$..ber <- jmvcore::OptionList$new(
                "ber",
                ber,
                options=list(
                    "0.01",
                    "0.05",
                    "0.10",
                    "0.20",
                    "0.5"),
                default="0.05")

            self$.addOption(private$..pc)
            self$.addOption(private$..pe)
            self$.addOption(private$..aer)
            self$.addOption(private$..ber)
        }),
    active = list(
        pc = function() private$..pc$value,
        pe = function() private$..pe$value,
        aer = function() private$..aer$value,
        ber = function() private$..ber$value),
    private = list(
        ..pc = NA,
        ..pe = NA,
        ..aer = NA,
        ..ber = NA)
)

SampleSizeCategoricalTIGResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeCategoricalTIGResults",
    inherit = jmvcore::Group,
    active = list(
        n = function() private$.items[["n"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample Size(Categorical Two Independent Groups)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="n",
                title="Sample Size(Categorical Two Independent Groups)"))}))

SampleSizeCategoricalTIGBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeCategoricalTIGBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Descriptive",
                name = "SampleSizeCategoricalTIG",
                version = c(1,0,0),
                options = options,
                results = SampleSizeCategoricalTIGResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Sample Size(Categorical Two Independent Groups)
#'
#' 
#' @param data .
#' @param pc .
#' @param pe .
#' @param aer .
#' @param ber .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$n} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
SampleSizeCategoricalTIG <- function(
    data,
    pc,
    pe,
    aer = "0.05",
    ber = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SampleSizeCategoricalTIG requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- SampleSizeCategoricalTIGOptions$new(
        pc = pc,
        pe = pe,
        aer = aer,
        ber = ber)

    analysis <- SampleSizeCategoricalTIGClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

