
# This file is automatically generated, you probably don't want to edit this

SampleSizeCategoricalTPSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeCategoricalTPSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            f = NULL,
            d = NULL,
            aer = "0.05",
            ber = "0.05", ...) {

            super$initialize(
                package="Descriptive",
                name="SampleSizeCategoricalTPS",
                requiresData=TRUE,
                ...)

            private$..f <- jmvcore::OptionNumber$new(
                "f",
                f)
            private$..d <- jmvcore::OptionNumber$new(
                "d",
                d)
            private$..aer <- jmvcore::OptionList$new(
                "aer",
                aer,
                options=list(
                    "0.005",
                    "0.01",
                    "0.025",
                    "0.05",
                    "0.0050",
                    "0.010",
                    "0.0250",
                    "0.050"),
                default="0.05")
            private$..ber <- jmvcore::OptionList$new(
                "ber",
                ber,
                options=list(
                    "0.01",
                    "0.05",
                    "0.10",
                    "0.20",
                    "0.5"),
                default="0.05")

            self$.addOption(private$..f)
            self$.addOption(private$..d)
            self$.addOption(private$..aer)
            self$.addOption(private$..ber)
        }),
    active = list(
        f = function() private$..f$value,
        d = function() private$..d$value,
        aer = function() private$..aer$value,
        ber = function() private$..ber$value),
    private = list(
        ..f = NA,
        ..d = NA,
        ..aer = NA,
        ..ber = NA)
)

SampleSizeCategoricalTPSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeCategoricalTPSResults",
    inherit = jmvcore::Group,
    active = list(
        n = function() private$.items[["n"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample Size(Categorical Two Paired Sample)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="n",
                title="Sample Size(Categorical Two Paired Sample)"))}))

SampleSizeCategoricalTPSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SampleSizeCategoricalTPSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Descriptive",
                name = "SampleSizeCategoricalTPS",
                version = c(1,0,0),
                options = options,
                results = SampleSizeCategoricalTPSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Sample Size(Categorical Two Paired Sample)
#'
#' 
#' @param data .
#' @param f .
#' @param d .
#' @param aer .
#' @param ber .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$n} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
SampleSizeCategoricalTPS <- function(
    data,
    f,
    d,
    aer = "0.05",
    ber = "0.05") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SampleSizeCategoricalTPS requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- SampleSizeCategoricalTPSOptions$new(
        f = f,
        d = d,
        aer = aer,
        ber = ber)

    analysis <- SampleSizeCategoricalTPSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

