
# This file is automatically generated, you probably don't want to edit this

CIPopulationMeanOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CIPopulationMeanOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            s = FALSE,
            x = NULL,
            m = NULL,
            sd = NULL,
            n = NULL,
            cl = "0.025",
            sn = TRUE,
            ksd = FALSE,
            psd = 0, ...) {

            super$initialize(
                package="Estimation",
                name="CIPopulationMean",
                requiresData=TRUE,
                ...)

            private$..s <- jmvcore::OptionBool$new(
                "s",
                s,
                default=FALSE)
            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..m <- jmvcore::OptionNumber$new(
                "m",
                m)
            private$..sd <- jmvcore::OptionNumber$new(
                "sd",
                sd)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n)
            private$..cl <- jmvcore::OptionList$new(
                "cl",
                cl,
                options=list(
                    "0.05",
                    "0.025",
                    "0.01",
                    "0.005"),
                default="0.025")
            private$..sn <- jmvcore::OptionBool$new(
                "sn",
                sn,
                default=TRUE)
            private$..ksd <- jmvcore::OptionBool$new(
                "ksd",
                ksd,
                default=FALSE)
            private$..psd <- jmvcore::OptionNumber$new(
                "psd",
                psd,
                default=0)

            self$.addOption(private$..s)
            self$.addOption(private$..x)
            self$.addOption(private$..m)
            self$.addOption(private$..sd)
            self$.addOption(private$..n)
            self$.addOption(private$..cl)
            self$.addOption(private$..sn)
            self$.addOption(private$..ksd)
            self$.addOption(private$..psd)
        }),
    active = list(
        s = function() private$..s$value,
        x = function() private$..x$value,
        m = function() private$..m$value,
        sd = function() private$..sd$value,
        n = function() private$..n$value,
        cl = function() private$..cl$value,
        sn = function() private$..sn$value,
        ksd = function() private$..ksd$value,
        psd = function() private$..psd$value),
    private = list(
        ..s = NA,
        ..x = NA,
        ..m = NA,
        ..sd = NA,
        ..n = NA,
        ..cl = NA,
        ..sn = NA,
        ..ksd = NA,
        ..psd = NA)
)

CIPopulationMeanResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CIPopulationMeanResults",
    inherit = jmvcore::Group,
    active = list(
        cl = function() private$.items[["cl"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Confidence Interval of Population Mean")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cl",
                title=""))}))

CIPopulationMeanBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CIPopulationMeanBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Estimation",
                name = "CIPopulationMean",
                version = c(1,0,0),
                options = options,
                results = CIPopulationMeanResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Confidence Interval of Population Mean
#'
#' 
#' @param data .
#' @param s .
#' @param x .
#' @param m .
#' @param sd .
#' @param n .
#' @param cl .
#' @param sn .
#' @param ksd .
#' @param psd .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$cl} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
CIPopulationMean <- function(
    data,
    s = FALSE,
    x,
    m,
    sd,
    n,
    cl = "0.025",
    sn = TRUE,
    ksd = FALSE,
    psd = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("CIPopulationMean requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL))


    options <- CIPopulationMeanOptions$new(
        s = s,
        x = x,
        m = m,
        sd = sd,
        n = n,
        cl = cl,
        sn = sn,
        ksd = ksd,
        psd = psd)

    analysis <- CIPopulationMeanClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

