
# This file is automatically generated, you probably don't want to edit this

FTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            raw = TRUE,
            var1 = NULL,
            n1 = NULL,
            var2 = NULL,
            n2 = NULL,
            x1 = NULL,
            x2 = NULL,
            a = "0.050", ...) {

            super$initialize(
                package="Estimation",
                name="FTest",
                requiresData=TRUE,
                ...)

            private$..raw <- jmvcore::OptionBool$new(
                "raw",
                raw,
                default=TRUE)
            private$..var1 <- jmvcore::OptionNumber$new(
                "var1",
                var1)
            private$..n1 <- jmvcore::OptionInteger$new(
                "n1",
                n1)
            private$..var2 <- jmvcore::OptionNumber$new(
                "var2",
                var2)
            private$..n2 <- jmvcore::OptionInteger$new(
                "n2",
                n2)
            private$..x1 <- jmvcore::OptionVariable$new(
                "x1",
                x1)
            private$..x2 <- jmvcore::OptionVariable$new(
                "x2",
                x2)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.0050",
                    "0.0250",
                    "0.050"),
                default="0.050")

            self$.addOption(private$..raw)
            self$.addOption(private$..var1)
            self$.addOption(private$..n1)
            self$.addOption(private$..var2)
            self$.addOption(private$..n2)
            self$.addOption(private$..x1)
            self$.addOption(private$..x2)
            self$.addOption(private$..a)
        }),
    active = list(
        raw = function() private$..raw$value,
        var1 = function() private$..var1$value,
        n1 = function() private$..n1$value,
        var2 = function() private$..var2$value,
        n2 = function() private$..n2$value,
        x1 = function() private$..x1$value,
        x2 = function() private$..x2$value,
        a = function() private$..a$value),
    private = list(
        ..raw = NA,
        ..var1 = NA,
        ..n1 = NA,
        ..var2 = NA,
        ..n2 = NA,
        ..x1 = NA,
        ..x2 = NA,
        ..a = NA)
)

FTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FTestResults",
    inherit = jmvcore::Group,
    active = list(
        conclusion = function() private$.items[["conclusion"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="F Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="conclusion",
                title=""))}))

FTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Estimation",
                name = "FTest",
                version = c(1,0,0),
                options = options,
                results = FTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' F Test
#'
#' 
#' @param data .
#' @param raw .
#' @param var1 .
#' @param n1 .
#' @param var2 .
#' @param n2 .
#' @param x1 .
#' @param x2 .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$conclusion} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
FTest <- function(
    data,
    raw = TRUE,
    var1,
    n1,
    var2,
    n2,
    x1,
    x2,
    a = "0.050") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("FTest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x1)) x1 <- jmvcore::resolveQuo(jmvcore::enquo(x1))
    if ( ! missing(x2)) x2 <- jmvcore::resolveQuo(jmvcore::enquo(x2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x1), x1, NULL),
            `if`( ! missing(x2), x2, NULL))


    options <- FTestOptions$new(
        raw = raw,
        var1 = var1,
        n1 = n1,
        var2 = var2,
        n2 = n2,
        x1 = x1,
        x2 = x2,
        a = a)

    analysis <- FTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

