
# This file is automatically generated, you probably don't want to edit this

NormalityTestKSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NormalityTestKSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            adjust = TRUE, ...) {

            super$initialize(
                package="Estimation",
                name="NormalityTestKS",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..adjust <- jmvcore::OptionBool$new(
                "adjust",
                adjust,
                default=TRUE)

            self$.addOption(private$..x)
            self$.addOption(private$..adjust)
        }),
    active = list(
        x = function() private$..x$value,
        adjust = function() private$..adjust$value),
    private = list(
        ..x = NA,
        ..adjust = NA)
)

NormalityTestKSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NormalityTestKSResults",
    inherit = jmvcore::Group,
    active = list(
        result = function() private$.items[["result"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Normality Test (Kolmogorov-Smirnov Test)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="result",
                title=""))}))

NormalityTestKSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NormalityTestKSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Estimation",
                name = "NormalityTestKS",
                version = c(1,0,0),
                options = options,
                results = NormalityTestKSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Normality Test (Kolmogorov-Smirnov Test)
#'
#' 
#' @param data .
#' @param x .
#' @param adjust .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$result} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
NormalityTestKS <- function(
    data,
    x,
    adjust = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("NormalityTestKS requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL))


    options <- NormalityTestKSOptions$new(
        x = x,
        adjust = adjust)

    analysis <- NormalityTestKSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

