
# This file is automatically generated, you probably don't want to edit this

NormalityTestEPOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NormalityTestEPOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL, ...) {

            super$initialize(
                package="Estimation",
                name="NormalityTestEP",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)

            self$.addOption(private$..x)
        }),
    active = list(
        x = function() private$..x$value),
    private = list(
        ..x = NA)
)

NormalityTestEPResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NormalityTestEPResults",
    inherit = jmvcore::Group,
    active = list(
        result = function() private$.items[["result"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Normality Test (Epps-Pulley Test)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="result",
                title=""))}))

NormalityTestEPBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NormalityTestEPBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Estimation",
                name = "NormalityTestEP",
                version = c(1,0,0),
                options = options,
                results = NormalityTestEPResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Normality Test (Epps-Pulley Test)
#'
#' 
#' @param data .
#' @param x .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$result} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
NormalityTestEP <- function(
    data,
    x) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("NormalityTestEP requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL))


    options <- NormalityTestEPOptions$new(
        x = x)

    analysis <- NormalityTestEPClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

