
# This file is automatically generated, you probably don't want to edit this

NormalityTestMomentOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NormalityTestMomentOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            a = "0.050", ...) {

            super$initialize(
                package="Estimation",
                name="NormalityTestMoment",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.0050",
                    "0.0250",
                    "0.050"),
                default="0.050")

            self$.addOption(private$..x)
            self$.addOption(private$..a)
        }),
    active = list(
        x = function() private$..x$value,
        a = function() private$..a$value),
    private = list(
        ..x = NA,
        ..a = NA)
)

NormalityTestMomentResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NormalityTestMomentResults",
    inherit = jmvcore::Group,
    active = list(
        conclusion = function() private$.items[["conclusion"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Normality Test(Method Of Moment)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="conclusion",
                title=""))}))

NormalityTestMomentBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NormalityTestMomentBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Estimation",
                name = "NormalityTestMoment",
                version = c(1,0,0),
                options = options,
                results = NormalityTestMomentResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Normality Test(Method Of Moment)
#'
#' 
#' @param data .
#' @param x .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$conclusion} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
NormalityTestMoment <- function(
    data,
    x,
    a = "0.050") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("NormalityTestMoment requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL))


    options <- NormalityTestMomentOptions$new(
        x = x,
        a = a)

    analysis <- NormalityTestMomentClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

