
# This file is automatically generated, you probably don't want to edit this

SatterthwaiteTTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SatterthwaiteTTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            raw = TRUE,
            m1 = NULL,
            sd1 = NULL,
            n1 = NULL,
            m2 = NULL,
            sd2 = NULL,
            n2 = NULL,
            s1 = NULL,
            s2 = NULL,
            a = "0.0250", ...) {

            super$initialize(
                package="Estimation",
                name="SatterthwaiteTTest",
                requiresData=TRUE,
                ...)

            private$..raw <- jmvcore::OptionBool$new(
                "raw",
                raw,
                default=TRUE)
            private$..m1 <- jmvcore::OptionNumber$new(
                "m1",
                m1)
            private$..sd1 <- jmvcore::OptionNumber$new(
                "sd1",
                sd1)
            private$..n1 <- jmvcore::OptionInteger$new(
                "n1",
                n1)
            private$..m2 <- jmvcore::OptionNumber$new(
                "m2",
                m2)
            private$..sd2 <- jmvcore::OptionNumber$new(
                "sd2",
                sd2)
            private$..n2 <- jmvcore::OptionInteger$new(
                "n2",
                n2)
            private$..s1 <- jmvcore::OptionVariable$new(
                "s1",
                s1)
            private$..s2 <- jmvcore::OptionVariable$new(
                "s2",
                s2)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.0050",
                    "0.01",
                    "0.0250",
                    "0.05",
                    "0.050",
                    "0.1"),
                default="0.0250")

            self$.addOption(private$..raw)
            self$.addOption(private$..m1)
            self$.addOption(private$..sd1)
            self$.addOption(private$..n1)
            self$.addOption(private$..m2)
            self$.addOption(private$..sd2)
            self$.addOption(private$..n2)
            self$.addOption(private$..s1)
            self$.addOption(private$..s2)
            self$.addOption(private$..a)
        }),
    active = list(
        raw = function() private$..raw$value,
        m1 = function() private$..m1$value,
        sd1 = function() private$..sd1$value,
        n1 = function() private$..n1$value,
        m2 = function() private$..m2$value,
        sd2 = function() private$..sd2$value,
        n2 = function() private$..n2$value,
        s1 = function() private$..s1$value,
        s2 = function() private$..s2$value,
        a = function() private$..a$value),
    private = list(
        ..raw = NA,
        ..m1 = NA,
        ..sd1 = NA,
        ..n1 = NA,
        ..m2 = NA,
        ..sd2 = NA,
        ..n2 = NA,
        ..s1 = NA,
        ..s2 = NA,
        ..a = NA)
)

SatterthwaiteTTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SatterthwaiteTTestResults",
    inherit = jmvcore::Group,
    active = list(
        conclusion = function() private$.items[["conclusion"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Satterwaite Approximate T-Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="conclusion",
                title=""))}))

SatterthwaiteTTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SatterthwaiteTTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Estimation",
                name = "SatterthwaiteTTest",
                version = c(1,0,0),
                options = options,
                results = SatterthwaiteTTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Satterwaite Approximate T-Test
#'
#' 
#' @param data .
#' @param raw .
#' @param m1 .
#' @param sd1 .
#' @param n1 .
#' @param m2 .
#' @param sd2 .
#' @param n2 .
#' @param s1 .
#' @param s2 .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$conclusion} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
SatterthwaiteTTest <- function(
    data,
    raw = TRUE,
    m1,
    sd1,
    n1,
    m2,
    sd2,
    n2,
    s1,
    s2,
    a = "0.0250") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SatterthwaiteTTest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(s1)) s1 <- jmvcore::resolveQuo(jmvcore::enquo(s1))
    if ( ! missing(s2)) s2 <- jmvcore::resolveQuo(jmvcore::enquo(s2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(s1), s1, NULL),
            `if`( ! missing(s2), s2, NULL))


    options <- SatterthwaiteTTestOptions$new(
        raw = raw,
        m1 = m1,
        sd1 = sd1,
        n1 = n1,
        m2 = m2,
        sd2 = sd2,
        n2 = n2,
        s1 = s1,
        s2 = s2,
        a = a)

    analysis <- SatterthwaiteTTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

