
# This file is automatically generated, you probably don't want to edit this

tDistributionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tDistributionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            v = NULL,
            vinf = FALSE, ...) {

            super$initialize(
                package="Estimation",
                name="tDistribution",
                requiresData=TRUE,
                ...)

            private$..v <- jmvcore::OptionVariable$new(
                "v",
                v)
            private$..vinf <- jmvcore::OptionBool$new(
                "vinf",
                vinf,
                default=FALSE)

            self$.addOption(private$..v)
            self$.addOption(private$..vinf)
        }),
    active = list(
        v = function() private$..v$value,
        vinf = function() private$..vinf$value),
    private = list(
        ..v = NA,
        ..vinf = NA)
)

tDistributionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tDistributionResults",
    inherit = jmvcore::Group,
    active = list(
        gtd = function() private$.items[["gtd"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="t-distribution")
            self$add(jmvcore::Image$new(
                options=options,
                name="gtd",
                title="Graph Of t-distribution",
                width=500,
                height=300,
                renderFun=".gtd"))}))

tDistributionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tDistributionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Estimation",
                name = "tDistribution",
                version = c(1,0,0),
                options = options,
                results = tDistributionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' t-distribution
#'
#' 
#' @param data .
#' @param v .
#' @param vinf .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$gtd} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
tDistribution <- function(
    data,
    v,
    vinf = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tDistribution requires jmvcore to be installed (restart may be required)")

    if ( ! missing(v)) v <- jmvcore::resolveQuo(jmvcore::enquo(v))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(v), v, NULL))


    options <- tDistributionOptions$new(
        v = v,
        vinf = vinf)

    analysis <- tDistributionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

