
# This file is automatically generated, you probably don't want to edit this

TwoSampleTTestEPVOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "TwoSampleTTestEPVOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            s1 = NULL,
            s2 = NULL,
            log = FALSE,
            a = "0.0250", ...) {

            super$initialize(
                package="Estimation",
                name="TwoSampleTTestEPV",
                requiresData=TRUE,
                ...)

            private$..s1 <- jmvcore::OptionVariable$new(
                "s1",
                s1)
            private$..s2 <- jmvcore::OptionVariable$new(
                "s2",
                s2)
            private$..log <- jmvcore::OptionBool$new(
                "log",
                log,
                default=FALSE)
            private$..a <- jmvcore::OptionList$new(
                "a",
                a,
                options=list(
                    "0.0050",
                    "0.01",
                    "0.0250",
                    "0.05",
                    "0.050",
                    "0.1"),
                default="0.0250")

            self$.addOption(private$..s1)
            self$.addOption(private$..s2)
            self$.addOption(private$..log)
            self$.addOption(private$..a)
        }),
    active = list(
        s1 = function() private$..s1$value,
        s2 = function() private$..s2$value,
        log = function() private$..log$value,
        a = function() private$..a$value),
    private = list(
        ..s1 = NA,
        ..s2 = NA,
        ..log = NA,
        ..a = NA)
)

TwoSampleTTestEPVResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "TwoSampleTTestEPVResults",
    inherit = jmvcore::Group,
    active = list(
        conclusion = function() private$.items[["conclusion"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Two-Sample T-Test(Equal Population Variances)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="conclusion",
                title=""))}))

TwoSampleTTestEPVBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "TwoSampleTTestEPVBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Estimation",
                name = "TwoSampleTTestEPV",
                version = c(1,0,0),
                options = options,
                results = TwoSampleTTestEPVResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Two-Sample T-Test(Equal Population Variances)
#'
#' 
#' @param data .
#' @param s1 .
#' @param s2 .
#' @param log .
#' @param a .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$conclusion} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
TwoSampleTTestEPV <- function(
    data,
    s1,
    s2,
    log = FALSE,
    a = "0.0250") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("TwoSampleTTestEPV requires jmvcore to be installed (restart may be required)")

    if ( ! missing(s1)) s1 <- jmvcore::resolveQuo(jmvcore::enquo(s1))
    if ( ! missing(s2)) s2 <- jmvcore::resolveQuo(jmvcore::enquo(s2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(s1), s1, NULL),
            `if`( ! missing(s2), s2, NULL))


    options <- TwoSampleTTestEPVOptions$new(
        s1 = s1,
        s2 = s2,
        log = log,
        a = a)

    analysis <- TwoSampleTTestEPVClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

